# Generated by pyside6-uic from widgets/rename_ihda/rename_ihda.ui. Do not edit; regenerate instead.
# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'rename_ihda.ui'
##
## Created by: Qt User Interface Compiler version 6.11.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QApplication, QDialog, QDialogButtonBox,
    QFrame, QHBoxLayout, QLabel, QLineEdit,
    QSizePolicy, QSpacerItem, QVBoxLayout, QWidget)
from . import rename_ihda_icons_rc

class Ui_Dialog__rename_ihda(object):
    def setupUi(self, Dialog__rename_ihda):
        if not Dialog__rename_ihda.objectName():
            Dialog__rename_ihda.setObjectName(u"Dialog__rename_ihda")
        Dialog__rename_ihda.resize(577, 202)
        font = QFont()
        font.setPointSize(11)
        Dialog__rename_ihda.setFont(font)
        icon = QIcon()
        icon.addFile(u":/main/icons/viewport_logo_trans.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        Dialog__rename_ihda.setWindowIcon(icon)
        self.verticalLayout_2 = QVBoxLayout(Dialog__rename_ihda)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.label__pixmap = QLabel(Dialog__rename_ihda)
        self.label__pixmap.setObjectName(u"label__pixmap")
        self.label__pixmap.setMaximumSize(QSize(50, 50))
        self.label__pixmap.setPixmap(QPixmap(u":/main/icons/ic_translate_white.png"))
        self.label__pixmap.setScaledContents(True)
        self.label__pixmap.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_7.addWidget(self.label__pixmap)

        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.label__old_ihda_name_prefix = QLabel(Dialog__rename_ihda)
        self.label__old_ihda_name_prefix.setObjectName(u"label__old_ihda_name_prefix")

        self.horizontalLayout_2.addWidget(self.label__old_ihda_name_prefix)

        self.label__old_ihda_name = QLabel(Dialog__rename_ihda)
        self.label__old_ihda_name.setObjectName(u"label__old_ihda_name")

        self.horizontalLayout_2.addWidget(self.label__old_ihda_name)


        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)

        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_5.addItem(self.horizontalSpacer_3)

        self.label__bridge = QLabel(Dialog__rename_ihda)
        self.label__bridge.setObjectName(u"label__bridge")
        self.label__bridge.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_5.addWidget(self.label__bridge)

        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalSpacer_4 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_4.addItem(self.horizontalSpacer_4)

        self.label__new_ihda_name_prefix = QLabel(Dialog__rename_ihda)
        self.label__new_ihda_name_prefix.setObjectName(u"label__new_ihda_name_prefix")

        self.horizontalLayout_4.addWidget(self.label__new_ihda_name_prefix)

        self.label__new_ihda_name = QLabel(Dialog__rename_ihda)
        self.label__new_ihda_name.setObjectName(u"label__new_ihda_name")

        self.horizontalLayout_4.addWidget(self.label__new_ihda_name)


        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)


        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_6.addItem(self.horizontalSpacer)


        self.verticalLayout.addLayout(self.horizontalLayout_6)

        self.line = QFrame(Dialog__rename_ihda)
        self.line.setObjectName(u"line")
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)

        self.verticalLayout.addWidget(self.line)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.label__input_ihda_name_prefix = QLabel(Dialog__rename_ihda)
        self.label__input_ihda_name_prefix.setObjectName(u"label__input_ihda_name_prefix")

        self.horizontalLayout.addWidget(self.label__input_ihda_name_prefix)

        self.lineEdit__input_ihda_name = QLineEdit(Dialog__rename_ihda)
        self.lineEdit__input_ihda_name.setObjectName(u"lineEdit__input_ihda_name")

        self.horizontalLayout.addWidget(self.lineEdit__input_ihda_name)


        self.verticalLayout.addLayout(self.horizontalLayout)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.label__confirm_ihda_name_pixmap = QLabel(Dialog__rename_ihda)
        self.label__confirm_ihda_name_pixmap.setObjectName(u"label__confirm_ihda_name_pixmap")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label__confirm_ihda_name_pixmap.sizePolicy().hasHeightForWidth())
        self.label__confirm_ihda_name_pixmap.setSizePolicy(sizePolicy)
        self.label__confirm_ihda_name_pixmap.setMinimumSize(QSize(22, 22))
        self.label__confirm_ihda_name_pixmap.setMaximumSize(QSize(24, 24))
        self.label__confirm_ihda_name_pixmap.setPixmap(QPixmap(u":/main/icons/ic_clear_white.png"))
        self.label__confirm_ihda_name_pixmap.setScaledContents(True)
        self.label__confirm_ihda_name_pixmap.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_3.addWidget(self.label__confirm_ihda_name_pixmap)

        self.label__confirm_ihda_name = QLabel(Dialog__rename_ihda)
        self.label__confirm_ihda_name.setObjectName(u"label__confirm_ihda_name")
        font1 = QFont()
        font1.setPointSize(12)
        self.label__confirm_ihda_name.setFont(font1)

        self.horizontalLayout_3.addWidget(self.label__confirm_ihda_name)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer_2)


        self.verticalLayout.addLayout(self.horizontalLayout_3)


        self.horizontalLayout_7.addLayout(self.verticalLayout)


        self.verticalLayout_2.addLayout(self.horizontalLayout_7)

        self.buttonBox__confirm = QDialogButtonBox(Dialog__rename_ihda)
        self.buttonBox__confirm.setObjectName(u"buttonBox__confirm")
        self.buttonBox__confirm.setLocale(QLocale(QLocale.Language.English, QLocale.Country.UnitedStates))
        self.buttonBox__confirm.setOrientation(Qt.Orientation.Horizontal)
        self.buttonBox__confirm.setStandardButtons(QDialogButtonBox.StandardButton.Cancel|QDialogButtonBox.StandardButton.Ok)

        self.verticalLayout_2.addWidget(self.buttonBox__confirm)


        self.retranslateUi(Dialog__rename_ihda)
        self.buttonBox__confirm.accepted.connect(Dialog__rename_ihda.accept)
        self.buttonBox__confirm.rejected.connect(Dialog__rename_ihda.reject)

        QMetaObject.connectSlotsByName(Dialog__rename_ihda)
    # setupUi

    def retranslateUi(self, Dialog__rename_ihda):
        Dialog__rename_ihda.setWindowTitle(QCoreApplication.translate("Dialog__rename_ihda", u"iHDA Rename", None))
        self.label__pixmap.setText("")
        self.label__old_ihda_name_prefix.setText(QCoreApplication.translate("Dialog__rename_ihda", u"OLD Name: ", None))
        self.label__old_ihda_name.setText("")
        self.label__bridge.setText(QCoreApplication.translate("Dialog__rename_ihda", u"----->", None))
        self.label__new_ihda_name_prefix.setText(QCoreApplication.translate("Dialog__rename_ihda", u"NEW Name: ", None))
        self.label__new_ihda_name.setText("")
        self.label__input_ihda_name_prefix.setText(QCoreApplication.translate("Dialog__rename_ihda", u"Input Name: ", None))
        self.lineEdit__input_ihda_name.setPlaceholderText(QCoreApplication.translate("Dialog__rename_ihda", u"Caution: Do not overlap with Houdini node type.", None))
        self.label__confirm_ihda_name_pixmap.setText("")
        self.label__confirm_ihda_name.setText("")
    # retranslateUi

