# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rename_ihda.ui',
# licensing of 'rename_ihda.ui' applies.
#
# Created: Tue May 26 00:10:18 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog__rename_ihda(object):
    def setupUi(self, Dialog__rename_ihda):
        Dialog__rename_ihda.setObjectName("Dialog__rename_ihda")
        Dialog__rename_ihda.resize(577, 202)
        font = QtGui.QFont()
        font.setPointSize(11)
        Dialog__rename_ihda.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/main/icons/viewport_logo_trans.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog__rename_ihda.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog__rename_ihda)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label__pixmap = QtWidgets.QLabel(Dialog__rename_ihda)
        self.label__pixmap.setMaximumSize(QtCore.QSize(50, 50))
        self.label__pixmap.setText("")
        self.label__pixmap.setPixmap(QtGui.QPixmap(":/main/icons/ic_translate_white.png"))
        self.label__pixmap.setScaledContents(True)
        self.label__pixmap.setAlignment(QtCore.Qt.AlignCenter)
        self.label__pixmap.setObjectName("label__pixmap")
        self.horizontalLayout_7.addWidget(self.label__pixmap)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label__old_ihda_name_prefix = QtWidgets.QLabel(Dialog__rename_ihda)
        self.label__old_ihda_name_prefix.setObjectName("label__old_ihda_name_prefix")
        self.horizontalLayout_2.addWidget(self.label__old_ihda_name_prefix)
        self.label__old_ihda_name = QtWidgets.QLabel(Dialog__rename_ihda)
        self.label__old_ihda_name.setText("")
        self.label__old_ihda_name.setObjectName("label__old_ihda_name")
        self.horizontalLayout_2.addWidget(self.label__old_ihda_name)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label__bridge = QtWidgets.QLabel(Dialog__rename_ihda)
        self.label__bridge.setAlignment(QtCore.Qt.AlignCenter)
        self.label__bridge.setObjectName("label__bridge")
        self.horizontalLayout_5.addWidget(self.label__bridge)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label__new_ihda_name_prefix = QtWidgets.QLabel(Dialog__rename_ihda)
        self.label__new_ihda_name_prefix.setObjectName("label__new_ihda_name_prefix")
        self.horizontalLayout_4.addWidget(self.label__new_ihda_name_prefix)
        self.label__new_ihda_name = QtWidgets.QLabel(Dialog__rename_ihda)
        self.label__new_ihda_name.setText("")
        self.label__new_ihda_name.setObjectName("label__new_ihda_name")
        self.horizontalLayout_4.addWidget(self.label__new_ihda_name)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.line = QtWidgets.QFrame(Dialog__rename_ihda)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label__input_ihda_name_prefix = QtWidgets.QLabel(Dialog__rename_ihda)
        self.label__input_ihda_name_prefix.setObjectName("label__input_ihda_name_prefix")
        self.horizontalLayout.addWidget(self.label__input_ihda_name_prefix)
        self.lineEdit__input_ihda_name = QtWidgets.QLineEdit(Dialog__rename_ihda)
        self.lineEdit__input_ihda_name.setObjectName("lineEdit__input_ihda_name")
        self.horizontalLayout.addWidget(self.lineEdit__input_ihda_name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label__confirm_ihda_name_pixmap = QtWidgets.QLabel(Dialog__rename_ihda)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label__confirm_ihda_name_pixmap.sizePolicy().hasHeightForWidth())
        self.label__confirm_ihda_name_pixmap.setSizePolicy(sizePolicy)
        self.label__confirm_ihda_name_pixmap.setMinimumSize(QtCore.QSize(22, 22))
        self.label__confirm_ihda_name_pixmap.setMaximumSize(QtCore.QSize(24, 24))
        self.label__confirm_ihda_name_pixmap.setText("")
        self.label__confirm_ihda_name_pixmap.setPixmap(QtGui.QPixmap(":/main/icons/ic_clear_white.png"))
        self.label__confirm_ihda_name_pixmap.setScaledContents(True)
        self.label__confirm_ihda_name_pixmap.setAlignment(QtCore.Qt.AlignCenter)
        self.label__confirm_ihda_name_pixmap.setObjectName("label__confirm_ihda_name_pixmap")
        self.horizontalLayout_3.addWidget(self.label__confirm_ihda_name_pixmap)
        self.label__confirm_ihda_name = QtWidgets.QLabel(Dialog__rename_ihda)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label__confirm_ihda_name.setFont(font)
        self.label__confirm_ihda_name.setText("")
        self.label__confirm_ihda_name.setObjectName("label__confirm_ihda_name")
        self.horizontalLayout_3.addWidget(self.label__confirm_ihda_name)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.buttonBox__confirm = QtWidgets.QDialogButtonBox(Dialog__rename_ihda)
        self.buttonBox__confirm.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox__confirm.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox__confirm.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox__confirm.setObjectName("buttonBox__confirm")
        self.verticalLayout_2.addWidget(self.buttonBox__confirm)

        self.retranslateUi(Dialog__rename_ihda)
        QtCore.QObject.connect(self.buttonBox__confirm, QtCore.SIGNAL("accepted()"), Dialog__rename_ihda.accept)
        QtCore.QObject.connect(self.buttonBox__confirm, QtCore.SIGNAL("rejected()"), Dialog__rename_ihda.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog__rename_ihda)

    def retranslateUi(self, Dialog__rename_ihda):
        Dialog__rename_ihda.setWindowTitle(QtWidgets.QApplication.translate("Dialog__rename_ihda", "iHDA Rename", None, -1))
        self.label__old_ihda_name_prefix.setText(QtWidgets.QApplication.translate("Dialog__rename_ihda", "OLD Name: ", None, -1))
        self.label__bridge.setText(QtWidgets.QApplication.translate("Dialog__rename_ihda", "----->", None, -1))
        self.label__new_ihda_name_prefix.setText(QtWidgets.QApplication.translate("Dialog__rename_ihda", "NEW Name: ", None, -1))
        self.label__input_ihda_name_prefix.setText(QtWidgets.QApplication.translate("Dialog__rename_ihda", "Input Name: ", None, -1))
        self.lineEdit__input_ihda_name.setPlaceholderText(QtWidgets.QApplication.translate("Dialog__rename_ihda", "Caution: Do not overlap with Houdini node type.", None, -1))

import rename_ihda_icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog__rename_ihda = QtWidgets.QDialog()
    ui = Ui_Dialog__rename_ihda()
    ui.setupUi(Dialog__rename_ihda)
    Dialog__rename_ihda.show()
    sys.exit(app.exec_())

