# Generated by pyside6-uic from widgets/make_video_info/make_video_info.ui. Do not edit; regenerate instead.
# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'make_video_info.ui'
##
## Created by: Qt User Interface Compiler version 6.11.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QApplication, QCheckBox, QComboBox,
    QDialog, QDialogButtonBox, QGroupBox, QHBoxLayout,
    QLabel, QSizePolicy, QSpacerItem, QSpinBox,
    QVBoxLayout, QWidget)
from . import icons_rc

class Ui_Dialog__makevideoinfo(object):
    def setupUi(self, Dialog__makevideoinfo):
        if not Dialog__makevideoinfo.objectName():
            Dialog__makevideoinfo.setObjectName(u"Dialog__makevideoinfo")
        Dialog__makevideoinfo.resize(642, 564)
        font = QFont()
        font.setPointSize(11)
        Dialog__makevideoinfo.setFont(font)
        icon = QIcon()
        icon.addFile(u":/main/icons/viewport_logo_trans.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        Dialog__makevideoinfo.setWindowIcon(icon)
        self.verticalLayout_4 = QVBoxLayout(Dialog__makevideoinfo)
        self.verticalLayout_4.setSpacing(12)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.label__company = QLabel(Dialog__makevideoinfo)
        self.label__company.setObjectName(u"label__company")
        self.label__company.setMaximumSize(QSize(30, 30))
        self.label__company.setPixmap(QPixmap(u":/main/icons/viewport_logo_trans.png"))
        self.label__company.setScaledContents(True)

        self.horizontalLayout_4.addWidget(self.label__company)

        self.label__title = QLabel(Dialog__makevideoinfo)
        self.label__title.setObjectName(u"label__title")
        font1 = QFont()
        font1.setPointSize(14)
        self.label__title.setFont(font1)
        self.label__title.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_4.addWidget(self.label__title)


        self.verticalLayout_4.addLayout(self.horizontalLayout_4)

        self.groupBox__share = QGroupBox(Dialog__makevideoinfo)
        self.groupBox__share.setObjectName(u"groupBox__share")
        self.horizontalLayout_12 = QHBoxLayout(self.groupBox__share)
        self.horizontalLayout_12.setObjectName(u"horizontalLayout_12")
        self.checkBox__youtube = QCheckBox(self.groupBox__share)
        self.checkBox__youtube.setObjectName(u"checkBox__youtube")
        icon1 = QIcon()
        icon1.addFile(u":/main/icons/youtube.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.checkBox__youtube.setIcon(icon1)
        self.checkBox__youtube.setIconSize(QSize(24, 24))

        self.horizontalLayout_12.addWidget(self.checkBox__youtube)

        self.checkBox__vimeo = QCheckBox(self.groupBox__share)
        self.checkBox__vimeo.setObjectName(u"checkBox__vimeo")
        icon2 = QIcon()
        icon2.addFile(u":/main/icons/vimeo.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.checkBox__vimeo.setIcon(icon2)
        self.checkBox__vimeo.setIconSize(QSize(24, 24))

        self.horizontalLayout_12.addWidget(self.checkBox__vimeo)

        self.horizontalSpacer_6 = QSpacerItem(144, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_12.addItem(self.horizontalSpacer_6)

        self.horizontalLayout_11 = QHBoxLayout()
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.horizontalLayout_10 = QHBoxLayout()
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.label__resolution_share = QLabel(self.groupBox__share)
        self.label__resolution_share.setObjectName(u"label__resolution_share")

        self.horizontalLayout_10.addWidget(self.label__resolution_share)

        self.comboBox__resolution_share = QComboBox(self.groupBox__share)
        self.comboBox__resolution_share.setObjectName(u"comboBox__resolution_share")
        self.comboBox__resolution_share.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.comboBox__resolution_share.setFrame(False)

        self.horizontalLayout_10.addWidget(self.comboBox__resolution_share)


        self.horizontalLayout_11.addLayout(self.horizontalLayout_10)

        self.label__confirm_resolution_share = QLabel(self.groupBox__share)
        self.label__confirm_resolution_share.setObjectName(u"label__confirm_resolution_share")

        self.horizontalLayout_11.addWidget(self.label__confirm_resolution_share)


        self.horizontalLayout_12.addLayout(self.horizontalLayout_11)


        self.verticalLayout_4.addWidget(self.groupBox__share)

        self.groupBox__video = QGroupBox(Dialog__makevideoinfo)
        self.groupBox__video.setObjectName(u"groupBox__video")
        self.verticalLayout_3 = QVBoxLayout(self.groupBox__video)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.label__sf = QLabel(self.groupBox__video)
        self.label__sf.setObjectName(u"label__sf")

        self.horizontalLayout.addWidget(self.label__sf)

        self.spinBox__sf = QSpinBox(self.groupBox__video)
        self.spinBox__sf.setObjectName(u"spinBox__sf")
        self.spinBox__sf.setFrame(False)
        self.spinBox__sf.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.spinBox__sf.setMaximum(9999999)
        self.spinBox__sf.setValue(1001)

        self.horizontalLayout.addWidget(self.spinBox__sf)


        self.horizontalLayout_3.addLayout(self.horizontalLayout)

        self.horizontalSpacer_4 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer_4)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.label__ef = QLabel(self.groupBox__video)
        self.label__ef.setObjectName(u"label__ef")

        self.horizontalLayout_2.addWidget(self.label__ef)

        self.spinBox__ef = QSpinBox(self.groupBox__video)
        self.spinBox__ef.setObjectName(u"spinBox__ef")
        self.spinBox__ef.setFrame(False)
        self.spinBox__ef.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.spinBox__ef.setMaximum(9999999)
        self.spinBox__ef.setValue(1240)

        self.horizontalLayout_2.addWidget(self.spinBox__ef)


        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)

        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer_3)


        self.verticalLayout_3.addLayout(self.horizontalLayout_3)

        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.label__fps = QLabel(self.groupBox__video)
        self.label__fps.setObjectName(u"label__fps")

        self.horizontalLayout_5.addWidget(self.label__fps)

        self.spinBox__fps = QSpinBox(self.groupBox__video)
        self.spinBox__fps.setObjectName(u"spinBox__fps")
        self.spinBox__fps.setFrame(False)
        self.spinBox__fps.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.spinBox__fps.setMinimum(1)
        self.spinBox__fps.setMaximum(120)
        self.spinBox__fps.setValue(24)

        self.horizontalLayout_5.addWidget(self.spinBox__fps)


        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_6.addItem(self.horizontalSpacer)


        self.verticalLayout_3.addLayout(self.horizontalLayout_6)

        self.horizontalLayout_8 = QHBoxLayout()
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.label__resolution = QLabel(self.groupBox__video)
        self.label__resolution.setObjectName(u"label__resolution")

        self.horizontalLayout_7.addWidget(self.label__resolution)

        self.comboBox__resolution = QComboBox(self.groupBox__video)
        self.comboBox__resolution.setObjectName(u"comboBox__resolution")
        self.comboBox__resolution.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.comboBox__resolution.setFrame(False)

        self.horizontalLayout_7.addWidget(self.comboBox__resolution)


        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_8.addItem(self.horizontalSpacer_2)

        self.label__confirm_resolution = QLabel(self.groupBox__video)
        self.label__confirm_resolution.setObjectName(u"label__confirm_resolution")

        self.horizontalLayout_8.addWidget(self.label__confirm_resolution)

        self.horizontalSpacer_5 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_8.addItem(self.horizontalSpacer_5)


        self.verticalLayout_3.addLayout(self.horizontalLayout_8)


        self.verticalLayout_4.addWidget(self.groupBox__video)

        self.groupBox__flipbook = QGroupBox(Dialog__makevideoinfo)
        self.groupBox__flipbook.setObjectName(u"groupBox__flipbook")
        self.horizontalLayout_9 = QHBoxLayout(self.groupBox__flipbook)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.checkBox__beautypassonly = QCheckBox(self.groupBox__flipbook)
        self.checkBox__beautypassonly.setObjectName(u"checkBox__beautypassonly")
        self.checkBox__beautypassonly.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.verticalLayout.addWidget(self.checkBox__beautypassonly)

        self.checkBox__render_all_viewports = QCheckBox(self.groupBox__flipbook)
        self.checkBox__render_all_viewports.setObjectName(u"checkBox__render_all_viewports")
        self.checkBox__render_all_viewports.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.verticalLayout.addWidget(self.checkBox__render_all_viewports)


        self.horizontalLayout_9.addLayout(self.verticalLayout)

        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.checkBox__use_motionblur = QCheckBox(self.groupBox__flipbook)
        self.checkBox__use_motionblur.setObjectName(u"checkBox__use_motionblur")
        self.checkBox__use_motionblur.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.verticalLayout_2.addWidget(self.checkBox__use_motionblur)

        self.checkBox__crop_out_mask_overlay = QCheckBox(self.groupBox__flipbook)
        self.checkBox__crop_out_mask_overlay.setObjectName(u"checkBox__crop_out_mask_overlay")
        self.checkBox__crop_out_mask_overlay.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.verticalLayout_2.addWidget(self.checkBox__crop_out_mask_overlay)

        self.checkBox__initialize_sim = QCheckBox(self.groupBox__flipbook)
        self.checkBox__initialize_sim.setObjectName(u"checkBox__initialize_sim")
        self.checkBox__initialize_sim.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.verticalLayout_2.addWidget(self.checkBox__initialize_sim)


        self.horizontalLayout_9.addLayout(self.verticalLayout_2)


        self.verticalLayout_4.addWidget(self.groupBox__flipbook)

        self.buttonBox__confirm = QDialogButtonBox(Dialog__makevideoinfo)
        self.buttonBox__confirm.setObjectName(u"buttonBox__confirm")
        self.buttonBox__confirm.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.buttonBox__confirm.setLocale(QLocale(QLocale.Language.English, QLocale.Country.UnitedStates))
        self.buttonBox__confirm.setOrientation(Qt.Orientation.Horizontal)
        self.buttonBox__confirm.setStandardButtons(QDialogButtonBox.StandardButton.Cancel|QDialogButtonBox.StandardButton.Ok)

        self.verticalLayout_4.addWidget(self.buttonBox__confirm)

#if QT_CONFIG(shortcut)
        self.label__sf.setBuddy(self.spinBox__sf)
        self.label__ef.setBuddy(self.spinBox__ef)
        self.label__fps.setBuddy(self.spinBox__sf)
#endif // QT_CONFIG(shortcut)

        self.retranslateUi(Dialog__makevideoinfo)
        self.buttonBox__confirm.accepted.connect(Dialog__makevideoinfo.accept)
        self.buttonBox__confirm.rejected.connect(Dialog__makevideoinfo.reject)

        QMetaObject.connectSlotsByName(Dialog__makevideoinfo)
    # setupUi

    def retranslateUi(self, Dialog__makevideoinfo):
        Dialog__makevideoinfo.setWindowTitle(QCoreApplication.translate("Dialog__makevideoinfo", u"Make Video Information", None))
        self.label__company.setText("")
        self.label__title.setText(QCoreApplication.translate("Dialog__makevideoinfo", u"Make Video Information", None))
        self.groupBox__share.setTitle(QCoreApplication.translate("Dialog__makevideoinfo", u"Share", None))
#if QT_CONFIG(tooltip)
        self.checkBox__youtube.setToolTip(QCoreApplication.translate("Dialog__makevideoinfo", u"Share Youtube", None))
#endif // QT_CONFIG(tooltip)
        self.checkBox__youtube.setText("")
#if QT_CONFIG(tooltip)
        self.checkBox__vimeo.setToolTip(QCoreApplication.translate("Dialog__makevideoinfo", u"Share Vimeo", None))
#endif // QT_CONFIG(tooltip)
        self.checkBox__vimeo.setText("")
        self.label__resolution_share.setText(QCoreApplication.translate("Dialog__makevideoinfo", u"Share Resolution", None))
#if QT_CONFIG(tooltip)
        self.comboBox__resolution_share.setToolTip(QCoreApplication.translate("Dialog__makevideoinfo", u"Set the resolution of SNS upload video.", None))
#endif // QT_CONFIG(tooltip)
        self.label__confirm_resolution_share.setText("")
        self.groupBox__video.setTitle(QCoreApplication.translate("Dialog__makevideoinfo", u"Video", None))
        self.label__sf.setText(QCoreApplication.translate("Dialog__makevideoinfo", u"Start Frame", None))
#if QT_CONFIG(tooltip)
        self.spinBox__sf.setToolTip(QCoreApplication.translate("Dialog__makevideoinfo", u"Set the frame range of the video.", None))
#endif // QT_CONFIG(tooltip)
        self.label__ef.setText(QCoreApplication.translate("Dialog__makevideoinfo", u"End Frame", None))
#if QT_CONFIG(tooltip)
        self.spinBox__ef.setToolTip(QCoreApplication.translate("Dialog__makevideoinfo", u"Set the frame range of the video.", None))
#endif // QT_CONFIG(tooltip)
        self.label__fps.setText(QCoreApplication.translate("Dialog__makevideoinfo", u"FPS (Frame Per Seconds)", None))
#if QT_CONFIG(tooltip)
        self.spinBox__fps.setToolTip(QCoreApplication.translate("Dialog__makevideoinfo", u"Set the FPS of the video.", None))
#endif // QT_CONFIG(tooltip)
        self.label__resolution.setText(QCoreApplication.translate("Dialog__makevideoinfo", u"Resolution", None))
#if QT_CONFIG(tooltip)
        self.comboBox__resolution.setToolTip(QCoreApplication.translate("Dialog__makevideoinfo", u"Set the resolution of images to render.", None))
#endif // QT_CONFIG(tooltip)
        self.label__confirm_resolution.setText("")
        self.groupBox__flipbook.setTitle(QCoreApplication.translate("Dialog__makevideoinfo", u"Flipbook", None))
#if QT_CONFIG(tooltip)
        self.checkBox__beautypassonly.setToolTip(QCoreApplication.translate("Dialog__makevideoinfo", u"Allows everything in the viewport to be rendered (False), or just the user geometry (True).", None))
#endif // QT_CONFIG(tooltip)
        self.checkBox__beautypassonly.setText(QCoreApplication.translate("Dialog__makevideoinfo", u"Beauty Pass Only", None))
#if QT_CONFIG(tooltip)
        self.checkBox__render_all_viewports.setToolTip(QCoreApplication.translate("Dialog__makevideoinfo", u"Render all visible viewports (True), or only the currently selected one.", None))
#endif // QT_CONFIG(tooltip)
        self.checkBox__render_all_viewports.setText(QCoreApplication.translate("Dialog__makevideoinfo", u"Render All Viewports", None))
#if QT_CONFIG(tooltip)
        self.checkBox__use_motionblur.setToolTip(QCoreApplication.translate("Dialog__makevideoinfo", u"Turn on motion blur.", None))
#endif // QT_CONFIG(tooltip)
        self.checkBox__use_motionblur.setText(QCoreApplication.translate("Dialog__makevideoinfo", u"Use Motion Blur", None))
#if QT_CONFIG(tooltip)
        self.checkBox__crop_out_mask_overlay.setToolTip(QCoreApplication.translate("Dialog__makevideoinfo", u"When enabled, the camera area is cropped out.", None))
#endif // QT_CONFIG(tooltip)
        self.checkBox__crop_out_mask_overlay.setText(QCoreApplication.translate("Dialog__makevideoinfo", u"Crop Out Mask Overlay", None))
#if QT_CONFIG(tooltip)
        self.checkBox__initialize_sim.setToolTip(QCoreApplication.translate("Dialog__makevideoinfo", u"When enabled, all simulations are re-initialized when the flipbook begins.", None))
#endif // QT_CONFIG(tooltip)
        self.checkBox__initialize_sim.setText(QCoreApplication.translate("Dialog__makevideoinfo", u"Initialize Simulations", None))
    # retranslateUi

