# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'make_video_info.ui',
# licensing of 'make_video_info.ui' applies.
#
# Created: Mon May 25 17:20:01 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog__makevideoinfo(object):
    def setupUi(self, Dialog__makevideoinfo):
        Dialog__makevideoinfo.setObjectName("Dialog__makevideoinfo")
        Dialog__makevideoinfo.resize(642, 564)
        font = QtGui.QFont()
        font.setPointSize(11)
        Dialog__makevideoinfo.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/main/icons/viewport_logo_trans.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog__makevideoinfo.setWindowIcon(icon)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Dialog__makevideoinfo)
        self.verticalLayout_4.setSpacing(12)
        self.verticalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label__company = QtWidgets.QLabel(Dialog__makevideoinfo)
        self.label__company.setMaximumSize(QtCore.QSize(30, 30))
        self.label__company.setText("")
        self.label__company.setPixmap(QtGui.QPixmap(":/main/icons/viewport_logo_trans.png"))
        self.label__company.setScaledContents(True)
        self.label__company.setObjectName("label__company")
        self.horizontalLayout_4.addWidget(self.label__company)
        self.label__title = QtWidgets.QLabel(Dialog__makevideoinfo)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label__title.setFont(font)
        self.label__title.setAlignment(QtCore.Qt.AlignCenter)
        self.label__title.setObjectName("label__title")
        self.horizontalLayout_4.addWidget(self.label__title)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.groupBox__share = QtWidgets.QGroupBox(Dialog__makevideoinfo)
        self.groupBox__share.setObjectName("groupBox__share")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox__share)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.checkBox__youtube = QtWidgets.QCheckBox(self.groupBox__share)
        self.checkBox__youtube.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/main/icons/youtube.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox__youtube.setIcon(icon1)
        self.checkBox__youtube.setIconSize(QtCore.QSize(24, 24))
        self.checkBox__youtube.setObjectName("checkBox__youtube")
        self.horizontalLayout_12.addWidget(self.checkBox__youtube)
        self.checkBox__vimeo = QtWidgets.QCheckBox(self.groupBox__share)
        self.checkBox__vimeo.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/main/icons/vimeo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox__vimeo.setIcon(icon2)
        self.checkBox__vimeo.setIconSize(QtCore.QSize(24, 24))
        self.checkBox__vimeo.setObjectName("checkBox__vimeo")
        self.horizontalLayout_12.addWidget(self.checkBox__vimeo)
        spacerItem = QtWidgets.QSpacerItem(144, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label__resolution_share = QtWidgets.QLabel(self.groupBox__share)
        self.label__resolution_share.setObjectName("label__resolution_share")
        self.horizontalLayout_10.addWidget(self.label__resolution_share)
        self.comboBox__resolution_share = QtWidgets.QComboBox(self.groupBox__share)
        self.comboBox__resolution_share.setCursor(QtCore.Qt.PointingHandCursor)
        self.comboBox__resolution_share.setFrame(False)
        self.comboBox__resolution_share.setObjectName("comboBox__resolution_share")
        self.horizontalLayout_10.addWidget(self.comboBox__resolution_share)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_10)
        self.label__confirm_resolution_share = QtWidgets.QLabel(self.groupBox__share)
        self.label__confirm_resolution_share.setText("")
        self.label__confirm_resolution_share.setObjectName("label__confirm_resolution_share")
        self.horizontalLayout_11.addWidget(self.label__confirm_resolution_share)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_11)
        self.verticalLayout_4.addWidget(self.groupBox__share)
        self.groupBox__video = QtWidgets.QGroupBox(Dialog__makevideoinfo)
        self.groupBox__video.setObjectName("groupBox__video")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox__video)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label__sf = QtWidgets.QLabel(self.groupBox__video)
        self.label__sf.setObjectName("label__sf")
        self.horizontalLayout.addWidget(self.label__sf)
        self.spinBox__sf = QtWidgets.QSpinBox(self.groupBox__video)
        self.spinBox__sf.setFrame(False)
        self.spinBox__sf.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox__sf.setMaximum(9999999)
        self.spinBox__sf.setProperty("value", 1001)
        self.spinBox__sf.setObjectName("spinBox__sf")
        self.horizontalLayout.addWidget(self.spinBox__sf)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label__ef = QtWidgets.QLabel(self.groupBox__video)
        self.label__ef.setObjectName("label__ef")
        self.horizontalLayout_2.addWidget(self.label__ef)
        self.spinBox__ef = QtWidgets.QSpinBox(self.groupBox__video)
        self.spinBox__ef.setFrame(False)
        self.spinBox__ef.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox__ef.setMaximum(9999999)
        self.spinBox__ef.setProperty("value", 1240)
        self.spinBox__ef.setObjectName("spinBox__ef")
        self.horizontalLayout_2.addWidget(self.spinBox__ef)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label__fps = QtWidgets.QLabel(self.groupBox__video)
        self.label__fps.setObjectName("label__fps")
        self.horizontalLayout_5.addWidget(self.label__fps)
        self.spinBox__fps = QtWidgets.QSpinBox(self.groupBox__video)
        self.spinBox__fps.setFrame(False)
        self.spinBox__fps.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox__fps.setMinimum(1)
        self.spinBox__fps.setMaximum(120)
        self.spinBox__fps.setProperty("value", 24)
        self.spinBox__fps.setObjectName("spinBox__fps")
        self.horizontalLayout_5.addWidget(self.spinBox__fps)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label__resolution = QtWidgets.QLabel(self.groupBox__video)
        self.label__resolution.setObjectName("label__resolution")
        self.horizontalLayout_7.addWidget(self.label__resolution)
        self.comboBox__resolution = QtWidgets.QComboBox(self.groupBox__video)
        self.comboBox__resolution.setCursor(QtCore.Qt.PointingHandCursor)
        self.comboBox__resolution.setFrame(False)
        self.comboBox__resolution.setObjectName("comboBox__resolution")
        self.horizontalLayout_7.addWidget(self.comboBox__resolution)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.label__confirm_resolution = QtWidgets.QLabel(self.groupBox__video)
        self.label__confirm_resolution.setText("")
        self.label__confirm_resolution.setObjectName("label__confirm_resolution")
        self.horizontalLayout_8.addWidget(self.label__confirm_resolution)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.verticalLayout_4.addWidget(self.groupBox__video)
        self.groupBox__flipbook = QtWidgets.QGroupBox(Dialog__makevideoinfo)
        self.groupBox__flipbook.setObjectName("groupBox__flipbook")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox__flipbook)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox__beautypassonly = QtWidgets.QCheckBox(self.groupBox__flipbook)
        self.checkBox__beautypassonly.setCursor(QtCore.Qt.PointingHandCursor)
        self.checkBox__beautypassonly.setObjectName("checkBox__beautypassonly")
        self.verticalLayout.addWidget(self.checkBox__beautypassonly)
        self.checkBox__render_all_viewports = QtWidgets.QCheckBox(self.groupBox__flipbook)
        self.checkBox__render_all_viewports.setCursor(QtCore.Qt.PointingHandCursor)
        self.checkBox__render_all_viewports.setObjectName("checkBox__render_all_viewports")
        self.verticalLayout.addWidget(self.checkBox__render_all_viewports)
        self.horizontalLayout_9.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox__use_motionblur = QtWidgets.QCheckBox(self.groupBox__flipbook)
        self.checkBox__use_motionblur.setCursor(QtCore.Qt.PointingHandCursor)
        self.checkBox__use_motionblur.setObjectName("checkBox__use_motionblur")
        self.verticalLayout_2.addWidget(self.checkBox__use_motionblur)
        self.checkBox__crop_out_mask_overlay = QtWidgets.QCheckBox(self.groupBox__flipbook)
        self.checkBox__crop_out_mask_overlay.setCursor(QtCore.Qt.PointingHandCursor)
        self.checkBox__crop_out_mask_overlay.setObjectName("checkBox__crop_out_mask_overlay")
        self.verticalLayout_2.addWidget(self.checkBox__crop_out_mask_overlay)
        self.checkBox__initialize_sim = QtWidgets.QCheckBox(self.groupBox__flipbook)
        self.checkBox__initialize_sim.setCursor(QtCore.Qt.PointingHandCursor)
        self.checkBox__initialize_sim.setObjectName("checkBox__initialize_sim")
        self.verticalLayout_2.addWidget(self.checkBox__initialize_sim)
        self.horizontalLayout_9.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addWidget(self.groupBox__flipbook)
        self.buttonBox__confirm = QtWidgets.QDialogButtonBox(Dialog__makevideoinfo)
        self.buttonBox__confirm.setCursor(QtCore.Qt.PointingHandCursor)
        self.buttonBox__confirm.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox__confirm.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox__confirm.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox__confirm.setObjectName("buttonBox__confirm")
        self.verticalLayout_4.addWidget(self.buttonBox__confirm)
        self.label__sf.setBuddy(self.spinBox__sf)
        self.label__ef.setBuddy(self.spinBox__ef)
        self.label__fps.setBuddy(self.spinBox__sf)

        self.retranslateUi(Dialog__makevideoinfo)
        QtCore.QObject.connect(self.buttonBox__confirm, QtCore.SIGNAL("accepted()"), Dialog__makevideoinfo.accept)
        QtCore.QObject.connect(self.buttonBox__confirm, QtCore.SIGNAL("rejected()"), Dialog__makevideoinfo.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog__makevideoinfo)

    def retranslateUi(self, Dialog__makevideoinfo):
        Dialog__makevideoinfo.setWindowTitle(QtWidgets.QApplication.translate("Dialog__makevideoinfo", "Make Video Information", None, -1))
        self.label__title.setText(QtWidgets.QApplication.translate("Dialog__makevideoinfo", "Make Video Information", None, -1))
        self.groupBox__share.setTitle(QtWidgets.QApplication.translate("Dialog__makevideoinfo", "Share", None, -1))
        self.checkBox__youtube.setToolTip(QtWidgets.QApplication.translate("Dialog__makevideoinfo", "Share Youtube", None, -1))
        self.checkBox__vimeo.setToolTip(QtWidgets.QApplication.translate("Dialog__makevideoinfo", "Share Vimeo", None, -1))
        self.label__resolution_share.setText(QtWidgets.QApplication.translate("Dialog__makevideoinfo", "Share Resolution", None, -1))
        self.comboBox__resolution_share.setToolTip(QtWidgets.QApplication.translate("Dialog__makevideoinfo", "Set the resolution of SNS upload video.", None, -1))
        self.groupBox__video.setTitle(QtWidgets.QApplication.translate("Dialog__makevideoinfo", "Video", None, -1))
        self.label__sf.setText(QtWidgets.QApplication.translate("Dialog__makevideoinfo", "Start Frame", None, -1))
        self.spinBox__sf.setToolTip(QtWidgets.QApplication.translate("Dialog__makevideoinfo", "Set the frame range of the video.", None, -1))
        self.label__ef.setText(QtWidgets.QApplication.translate("Dialog__makevideoinfo", "End Frame", None, -1))
        self.spinBox__ef.setToolTip(QtWidgets.QApplication.translate("Dialog__makevideoinfo", "Set the frame range of the video.", None, -1))
        self.label__fps.setText(QtWidgets.QApplication.translate("Dialog__makevideoinfo", "FPS (Frame Per Seconds)", None, -1))
        self.spinBox__fps.setToolTip(QtWidgets.QApplication.translate("Dialog__makevideoinfo", "Set the FPS of the video.", None, -1))
        self.label__resolution.setText(QtWidgets.QApplication.translate("Dialog__makevideoinfo", "Resolution", None, -1))
        self.comboBox__resolution.setToolTip(QtWidgets.QApplication.translate("Dialog__makevideoinfo", "Set the resolution of images to render.", None, -1))
        self.groupBox__flipbook.setTitle(QtWidgets.QApplication.translate("Dialog__makevideoinfo", "Flipbook", None, -1))
        self.checkBox__beautypassonly.setToolTip(QtWidgets.QApplication.translate("Dialog__makevideoinfo", "Allows everything in the viewport to be rendered (False), or just the user geometry (True).", None, -1))
        self.checkBox__beautypassonly.setText(QtWidgets.QApplication.translate("Dialog__makevideoinfo", "Beauty Pass Only", None, -1))
        self.checkBox__render_all_viewports.setToolTip(QtWidgets.QApplication.translate("Dialog__makevideoinfo", "Render all visible viewports (True), or only the currently selected one.", None, -1))
        self.checkBox__render_all_viewports.setText(QtWidgets.QApplication.translate("Dialog__makevideoinfo", "Render All Viewports", None, -1))
        self.checkBox__use_motionblur.setToolTip(QtWidgets.QApplication.translate("Dialog__makevideoinfo", "Turn on motion blur.", None, -1))
        self.checkBox__use_motionblur.setText(QtWidgets.QApplication.translate("Dialog__makevideoinfo", "Use Motion Blur", None, -1))
        self.checkBox__crop_out_mask_overlay.setToolTip(QtWidgets.QApplication.translate("Dialog__makevideoinfo", "When enabled, the camera area is cropped out.", None, -1))
        self.checkBox__crop_out_mask_overlay.setText(QtWidgets.QApplication.translate("Dialog__makevideoinfo", "Crop Out Mask Overlay", None, -1))
        self.checkBox__initialize_sim.setToolTip(QtWidgets.QApplication.translate("Dialog__makevideoinfo", "When enabled, all simulations are re-initialized when the flipbook begins.", None, -1))
        self.checkBox__initialize_sim.setText(QtWidgets.QApplication.translate("Dialog__makevideoinfo", "Initialize Simulations", None, -1))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog__makevideoinfo = QtWidgets.QDialog()
    ui = Ui_Dialog__makevideoinfo()
    ui.setupUi(Dialog__makevideoinfo)
    Dialog__makevideoinfo.show()
    sys.exit(app.exec_())

