# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preference.ui',
# licensing of 'preference.ui' applies.
#
# Created: Fri May 29 21:09:48 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog__preference(object):
    def setupUi(self, Dialog__preference):
        Dialog__preference.setObjectName("Dialog__preference")
        Dialog__preference.resize(817, 889)
        font = QtGui.QFont()
        font.setPointSize(11)
        Dialog__preference.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/main/icons/viewport_logo_trans.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog__preference.setWindowIcon(icon)
        Dialog__preference.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(Dialog__preference)
        self.verticalLayout_13.setSpacing(5)
        self.verticalLayout_13.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.groupBox__data = QtWidgets.QGroupBox(Dialog__preference)
        self.groupBox__data.setObjectName("groupBox__data")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox__data)
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label__pixmap = QtWidgets.QLabel(self.groupBox__data)
        self.label__pixmap.setMaximumSize(QtCore.QSize(55, 55))
        self.label__pixmap.setText("")
        self.label__pixmap.setPixmap(QtGui.QPixmap(":/main/icons/ic_settings_white.png"))
        self.label__pixmap.setScaledContents(True)
        self.label__pixmap.setAlignment(QtCore.Qt.AlignCenter)
        self.label__pixmap.setObjectName("label__pixmap")
        self.horizontalLayout_3.addWidget(self.label__pixmap)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label__data_dirpath = QtWidgets.QLabel(self.groupBox__data)
        self.label__data_dirpath.setObjectName("label__data_dirpath")
        self.horizontalLayout.addWidget(self.label__data_dirpath)
        self.lineEdit__data_dirpath = QtWidgets.QLineEdit(self.groupBox__data)
        self.lineEdit__data_dirpath.setObjectName("lineEdit__data_dirpath")
        self.horizontalLayout.addWidget(self.lineEdit__data_dirpath)
        self.toolButton__select_data_dirpath = QtWidgets.QToolButton(self.groupBox__data)
        self.toolButton__select_data_dirpath.setCursor(QtCore.Qt.PointingHandCursor)
        self.toolButton__select_data_dirpath.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/main/icons/ic_folder_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton__select_data_dirpath.setIcon(icon1)
        self.toolButton__select_data_dirpath.setIconSize(QtCore.QSize(20, 20))
        self.toolButton__select_data_dirpath.setObjectName("toolButton__select_data_dirpath")
        self.horizontalLayout.addWidget(self.toolButton__select_data_dirpath)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label__result_show = QtWidgets.QLabel(self.groupBox__data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label__result_show.sizePolicy().hasHeightForWidth())
        self.label__result_show.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label__result_show.setFont(font)
        self.label__result_show.setObjectName("label__result_show")
        self.horizontalLayout_2.addWidget(self.label__result_show)
        self.lineEdit__result = QtWidgets.QLineEdit(self.groupBox__data)
        self.lineEdit__result.setReadOnly(True)
        self.lineEdit__result.setObjectName("lineEdit__result")
        self.horizontalLayout_2.addWidget(self.lineEdit__result)
        self.label__valid_chk_pixmap = QtWidgets.QLabel(self.groupBox__data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label__valid_chk_pixmap.sizePolicy().hasHeightForWidth())
        self.label__valid_chk_pixmap.setSizePolicy(sizePolicy)
        self.label__valid_chk_pixmap.setMaximumSize(QtCore.QSize(24, 24))
        self.label__valid_chk_pixmap.setText("")
        self.label__valid_chk_pixmap.setPixmap(QtGui.QPixmap(":/main/icons/ic_clear_white.png"))
        self.label__valid_chk_pixmap.setScaledContents(True)
        self.label__valid_chk_pixmap.setAlignment(QtCore.Qt.AlignCenter)
        self.label__valid_chk_pixmap.setObjectName("label__valid_chk_pixmap")
        self.horizontalLayout_2.addWidget(self.label__valid_chk_pixmap)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_13.addWidget(self.groupBox__data)
        self.groupBox__ffmpeg = QtWidgets.QGroupBox(Dialog__preference)
        self.groupBox__ffmpeg.setObjectName("groupBox__ffmpeg")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox__ffmpeg)
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label__ffmpeg_pixmap = QtWidgets.QLabel(self.groupBox__ffmpeg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label__ffmpeg_pixmap.sizePolicy().hasHeightForWidth())
        self.label__ffmpeg_pixmap.setSizePolicy(sizePolicy)
        self.label__ffmpeg_pixmap.setMaximumSize(QtCore.QSize(55, 55))
        self.label__ffmpeg_pixmap.setText("")
        self.label__ffmpeg_pixmap.setPixmap(QtGui.QPixmap(":/main/icons/ffmpeg.png"))
        self.label__ffmpeg_pixmap.setScaledContents(True)
        self.label__ffmpeg_pixmap.setAlignment(QtCore.Qt.AlignCenter)
        self.label__ffmpeg_pixmap.setObjectName("label__ffmpeg_pixmap")
        self.horizontalLayout_4.addWidget(self.label__ffmpeg_pixmap)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label__ffmpeg_dirpath = QtWidgets.QLabel(self.groupBox__ffmpeg)
        self.label__ffmpeg_dirpath.setObjectName("label__ffmpeg_dirpath")
        self.horizontalLayout_5.addWidget(self.label__ffmpeg_dirpath)
        self.lineEdit__ffmpeg_dirpath = QtWidgets.QLineEdit(self.groupBox__ffmpeg)
        self.lineEdit__ffmpeg_dirpath.setObjectName("lineEdit__ffmpeg_dirpath")
        self.horizontalLayout_5.addWidget(self.lineEdit__ffmpeg_dirpath)
        self.toolButton__select_ffmpeg_dirpath = QtWidgets.QToolButton(self.groupBox__ffmpeg)
        self.toolButton__select_ffmpeg_dirpath.setCursor(QtCore.Qt.PointingHandCursor)
        self.toolButton__select_ffmpeg_dirpath.setText("")
        self.toolButton__select_ffmpeg_dirpath.setIcon(icon1)
        self.toolButton__select_ffmpeg_dirpath.setIconSize(QtCore.QSize(20, 20))
        self.toolButton__select_ffmpeg_dirpath.setObjectName("toolButton__select_ffmpeg_dirpath")
        self.horizontalLayout_5.addWidget(self.toolButton__select_ffmpeg_dirpath)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label__ffmpeg_result_show = QtWidgets.QLabel(self.groupBox__ffmpeg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label__ffmpeg_result_show.sizePolicy().hasHeightForWidth())
        self.label__ffmpeg_result_show.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label__ffmpeg_result_show.setFont(font)
        self.label__ffmpeg_result_show.setObjectName("label__ffmpeg_result_show")
        self.horizontalLayout_6.addWidget(self.label__ffmpeg_result_show)
        self.lineEdit__ffmpeg_result = QtWidgets.QLineEdit(self.groupBox__ffmpeg)
        self.lineEdit__ffmpeg_result.setReadOnly(True)
        self.lineEdit__ffmpeg_result.setObjectName("lineEdit__ffmpeg_result")
        self.horizontalLayout_6.addWidget(self.lineEdit__ffmpeg_result)
        self.label__ffmpeg_valid_chk_pixmap = QtWidgets.QLabel(self.groupBox__ffmpeg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label__ffmpeg_valid_chk_pixmap.sizePolicy().hasHeightForWidth())
        self.label__ffmpeg_valid_chk_pixmap.setSizePolicy(sizePolicy)
        self.label__ffmpeg_valid_chk_pixmap.setMaximumSize(QtCore.QSize(24, 24))
        self.label__ffmpeg_valid_chk_pixmap.setText("")
        self.label__ffmpeg_valid_chk_pixmap.setPixmap(QtGui.QPixmap(":/main/icons/ic_clear_white.png"))
        self.label__ffmpeg_valid_chk_pixmap.setScaledContents(True)
        self.label__ffmpeg_valid_chk_pixmap.setAlignment(QtCore.Qt.AlignCenter)
        self.label__ffmpeg_valid_chk_pixmap.setObjectName("label__ffmpeg_valid_chk_pixmap")
        self.horizontalLayout_6.addWidget(self.label__ffmpeg_valid_chk_pixmap)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_13.addWidget(self.groupBox__ffmpeg)
        self.groupBox__app_properties = QtWidgets.QGroupBox(Dialog__preference)
        self.groupBox__app_properties.setObjectName("groupBox__app_properties")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.groupBox__app_properties)
        self.horizontalLayout_34.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.pushButton__reset_default_app_properties = QtWidgets.QPushButton(self.groupBox__app_properties)
        self.pushButton__reset_default_app_properties.setMaximumSize(QtCore.QSize(55, 55))
        self.pushButton__reset_default_app_properties.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton__reset_default_app_properties.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/main/icons/ic_refresh_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton__reset_default_app_properties.setIcon(icon2)
        self.pushButton__reset_default_app_properties.setIconSize(QtCore.QSize(50, 50))
        self.pushButton__reset_default_app_properties.setFlat(True)
        self.pushButton__reset_default_app_properties.setObjectName("pushButton__reset_default_app_properties")
        self.horizontalLayout_34.addWidget(self.pushButton__reset_default_app_properties)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox__app_properties)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label__default_main_icon_size = QtWidgets.QLabel(self.groupBox)
        self.label__default_main_icon_size.setObjectName("label__default_main_icon_size")
        self.horizontalLayout_33.addWidget(self.label__default_main_icon_size)
        self.spinBox__default_main_icon_size = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox__default_main_icon_size.setCursor(QtCore.Qt.PointingHandCursor)
        self.spinBox__default_main_icon_size.setFrame(False)
        self.spinBox__default_main_icon_size.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox__default_main_icon_size.setMinimum(1)
        self.spinBox__default_main_icon_size.setMaximum(30)
        self.spinBox__default_main_icon_size.setProperty("value", 20)
        self.spinBox__default_main_icon_size.setObjectName("spinBox__default_main_icon_size")
        self.horizontalLayout_33.addWidget(self.spinBox__default_main_icon_size)
        self.verticalLayout_11.addLayout(self.horizontalLayout_33)
        self.verticalLayout_12.addWidget(self.groupBox)
        self.groupBox__default_icon = QtWidgets.QGroupBox(self.groupBox__app_properties)
        self.groupBox__default_icon.setObjectName("groupBox__default_icon")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox__default_icon)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label__view_font_size = QtWidgets.QLabel(self.groupBox__default_icon)
        self.label__view_font_size.setObjectName("label__view_font_size")
        self.horizontalLayout_10.addWidget(self.label__view_font_size)
        self.spinBox__view_font_size = QtWidgets.QSpinBox(self.groupBox__default_icon)
        self.spinBox__view_font_size.setCursor(QtCore.Qt.PointingHandCursor)
        self.spinBox__view_font_size.setFrame(False)
        self.spinBox__view_font_size.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox__view_font_size.setMinimum(2)
        self.spinBox__view_font_size.setMaximum(50)
        self.spinBox__view_font_size.setProperty("value", 11)
        self.spinBox__view_font_size.setObjectName("spinBox__view_font_size")
        self.horizontalLayout_10.addWidget(self.spinBox__view_font_size)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_10)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label__view_font_style = QtWidgets.QLabel(self.groupBox__default_icon)
        self.label__view_font_style.setObjectName("label__view_font_style")
        self.horizontalLayout_8.addWidget(self.label__view_font_style)
        self.fontComboBox__view_font_style = QtWidgets.QFontComboBox(self.groupBox__default_icon)
        self.fontComboBox__view_font_style.setCursor(QtCore.Qt.PointingHandCursor)
        self.fontComboBox__view_font_style.setFrame(False)
        self.fontComboBox__view_font_style.setObjectName("fontComboBox__view_font_style")
        self.horizontalLayout_8.addWidget(self.fontComboBox__view_font_style)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.line = QtWidgets.QFrame(self.groupBox__default_icon)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_10.addWidget(self.line)
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox__default_icon)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setObjectName("tabWidget")
        self.tab__icon = QtWidgets.QWidget()
        self.tab__icon.setObjectName("tab__icon")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab__icon)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(15)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label__default_listview_icon_size = QtWidgets.QLabel(self.tab__icon)
        self.label__default_listview_icon_size.setObjectName("label__default_listview_icon_size")
        self.horizontalLayout_11.addWidget(self.label__default_listview_icon_size)
        self.spinBox__default_listview_icon_size = QtWidgets.QSpinBox(self.tab__icon)
        self.spinBox__default_listview_icon_size.setCursor(QtCore.Qt.PointingHandCursor)
        self.spinBox__default_listview_icon_size.setFrame(False)
        self.spinBox__default_listview_icon_size.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox__default_listview_icon_size.setMinimum(1)
        self.spinBox__default_listview_icon_size.setProperty("value", 38)
        self.spinBox__default_listview_icon_size.setObjectName("spinBox__default_listview_icon_size")
        self.horizontalLayout_11.addWidget(self.spinBox__default_listview_icon_size)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_11)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label__default_listview_thumb_scale = QtWidgets.QLabel(self.tab__icon)
        self.label__default_listview_thumb_scale.setObjectName("label__default_listview_thumb_scale")
        self.horizontalLayout_13.addWidget(self.label__default_listview_thumb_scale)
        self.doubleSpinBox__default_listview_thumb_scale = QtWidgets.QDoubleSpinBox(self.tab__icon)
        self.doubleSpinBox__default_listview_thumb_scale.setFrame(False)
        self.doubleSpinBox__default_listview_thumb_scale.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__default_listview_thumb_scale.setDecimals(1)
        self.doubleSpinBox__default_listview_thumb_scale.setMinimum(0.1)
        self.doubleSpinBox__default_listview_thumb_scale.setMaximum(50.0)
        self.doubleSpinBox__default_listview_thumb_scale.setSingleStep(0.1)
        self.doubleSpinBox__default_listview_thumb_scale.setProperty("value", 2.0)
        self.doubleSpinBox__default_listview_thumb_scale.setObjectName("doubleSpinBox__default_listview_thumb_scale")
        self.horizontalLayout_13.addWidget(self.doubleSpinBox__default_listview_thumb_scale)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_13)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(15)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label__default_tableview_icon_size = QtWidgets.QLabel(self.tab__icon)
        self.label__default_tableview_icon_size.setObjectName("label__default_tableview_icon_size")
        self.horizontalLayout_12.addWidget(self.label__default_tableview_icon_size)
        self.spinBox__default_tableview_icon_size = QtWidgets.QSpinBox(self.tab__icon)
        self.spinBox__default_tableview_icon_size.setCursor(QtCore.Qt.PointingHandCursor)
        self.spinBox__default_tableview_icon_size.setFrame(False)
        self.spinBox__default_tableview_icon_size.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox__default_tableview_icon_size.setMinimum(1)
        self.spinBox__default_tableview_icon_size.setProperty("value", 38)
        self.spinBox__default_tableview_icon_size.setObjectName("spinBox__default_tableview_icon_size")
        self.horizontalLayout_12.addWidget(self.spinBox__default_tableview_icon_size)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_12)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem3)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label__default_tableview_thumb_scale = QtWidgets.QLabel(self.tab__icon)
        self.label__default_tableview_thumb_scale.setObjectName("label__default_tableview_thumb_scale")
        self.horizontalLayout_15.addWidget(self.label__default_tableview_thumb_scale)
        self.doubleSpinBox__default_tableview_thumb_scale = QtWidgets.QDoubleSpinBox(self.tab__icon)
        self.doubleSpinBox__default_tableview_thumb_scale.setFrame(False)
        self.doubleSpinBox__default_tableview_thumb_scale.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__default_tableview_thumb_scale.setDecimals(1)
        self.doubleSpinBox__default_tableview_thumb_scale.setMinimum(0.1)
        self.doubleSpinBox__default_tableview_thumb_scale.setMaximum(50.0)
        self.doubleSpinBox__default_tableview_thumb_scale.setSingleStep(0.1)
        self.doubleSpinBox__default_tableview_thumb_scale.setProperty("value", 1.3)
        self.doubleSpinBox__default_tableview_thumb_scale.setObjectName("doubleSpinBox__default_tableview_thumb_scale")
        self.horizontalLayout_15.addWidget(self.doubleSpinBox__default_tableview_thumb_scale)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem4)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_15)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label__default_treeview_icon_size = QtWidgets.QLabel(self.tab__icon)
        self.label__default_treeview_icon_size.setObjectName("label__default_treeview_icon_size")
        self.horizontalLayout_9.addWidget(self.label__default_treeview_icon_size)
        self.spinBox__default_treeview_icon_size = QtWidgets.QSpinBox(self.tab__icon)
        self.spinBox__default_treeview_icon_size.setCursor(QtCore.Qt.PointingHandCursor)
        self.spinBox__default_treeview_icon_size.setFrame(False)
        self.spinBox__default_treeview_icon_size.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox__default_treeview_icon_size.setMinimum(1)
        self.spinBox__default_treeview_icon_size.setProperty("value", 24)
        self.spinBox__default_treeview_icon_size.setObjectName("spinBox__default_treeview_icon_size")
        self.horizontalLayout_9.addWidget(self.spinBox__default_treeview_icon_size)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/main/icons/ic_photo_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab__icon, icon3, "")
        self.tab__padding = QtWidgets.QWidget()
        self.tab__padding.setObjectName("tab__padding")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.tab__padding)
        self.horizontalLayout_32.setSpacing(5)
        self.horizontalLayout_32.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label__default_list_item_padding = QtWidgets.QLabel(self.tab__padding)
        self.label__default_list_item_padding.setObjectName("label__default_list_item_padding")
        self.horizontalLayout_29.addWidget(self.label__default_list_item_padding)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem6)
        self.doubleSpinBox__default_list_item_padding = QtWidgets.QDoubleSpinBox(self.tab__padding)
        self.doubleSpinBox__default_list_item_padding.setFrame(False)
        self.doubleSpinBox__default_list_item_padding.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__default_list_item_padding.setDecimals(1)
        self.doubleSpinBox__default_list_item_padding.setMinimum(0.0)
        self.doubleSpinBox__default_list_item_padding.setMaximum(100.0)
        self.doubleSpinBox__default_list_item_padding.setSingleStep(0.1)
        self.doubleSpinBox__default_list_item_padding.setProperty("value", 20.0)
        self.doubleSpinBox__default_list_item_padding.setObjectName("doubleSpinBox__default_list_item_padding")
        self.horizontalLayout_29.addWidget(self.doubleSpinBox__default_list_item_padding)
        self.verticalLayout_9.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label__default_table_item_padding = QtWidgets.QLabel(self.tab__padding)
        self.label__default_table_item_padding.setObjectName("label__default_table_item_padding")
        self.horizontalLayout_30.addWidget(self.label__default_table_item_padding)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem7)
        self.doubleSpinBox__default_table_item_padding = QtWidgets.QDoubleSpinBox(self.tab__padding)
        self.doubleSpinBox__default_table_item_padding.setFrame(False)
        self.doubleSpinBox__default_table_item_padding.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__default_table_item_padding.setDecimals(1)
        self.doubleSpinBox__default_table_item_padding.setMinimum(0.0)
        self.doubleSpinBox__default_table_item_padding.setMaximum(100.0)
        self.doubleSpinBox__default_table_item_padding.setSingleStep(0.1)
        self.doubleSpinBox__default_table_item_padding.setProperty("value", 0.0)
        self.doubleSpinBox__default_table_item_padding.setObjectName("doubleSpinBox__default_table_item_padding")
        self.horizontalLayout_30.addWidget(self.doubleSpinBox__default_table_item_padding)
        self.verticalLayout_9.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label__default_history_item_padding = QtWidgets.QLabel(self.tab__padding)
        self.label__default_history_item_padding.setObjectName("label__default_history_item_padding")
        self.horizontalLayout_31.addWidget(self.label__default_history_item_padding)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem8)
        self.doubleSpinBox__default_history_item_padding = QtWidgets.QDoubleSpinBox(self.tab__padding)
        self.doubleSpinBox__default_history_item_padding.setFrame(False)
        self.doubleSpinBox__default_history_item_padding.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__default_history_item_padding.setDecimals(1)
        self.doubleSpinBox__default_history_item_padding.setMinimum(0.0)
        self.doubleSpinBox__default_history_item_padding.setMaximum(100.0)
        self.doubleSpinBox__default_history_item_padding.setSingleStep(0.1)
        self.doubleSpinBox__default_history_item_padding.setProperty("value", 0.0)
        self.doubleSpinBox__default_history_item_padding.setObjectName("doubleSpinBox__default_history_item_padding")
        self.horizontalLayout_31.addWidget(self.doubleSpinBox__default_history_item_padding)
        self.verticalLayout_9.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32.addLayout(self.verticalLayout_9)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label__default_cate_item_padding = QtWidgets.QLabel(self.tab__padding)
        self.label__default_cate_item_padding.setObjectName("label__default_cate_item_padding")
        self.horizontalLayout_26.addWidget(self.label__default_cate_item_padding)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem10)
        self.doubleSpinBox__default_cate_item_padding = QtWidgets.QDoubleSpinBox(self.tab__padding)
        self.doubleSpinBox__default_cate_item_padding.setFrame(False)
        self.doubleSpinBox__default_cate_item_padding.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__default_cate_item_padding.setDecimals(1)
        self.doubleSpinBox__default_cate_item_padding.setMinimum(0.0)
        self.doubleSpinBox__default_cate_item_padding.setMaximum(100.0)
        self.doubleSpinBox__default_cate_item_padding.setSingleStep(0.1)
        self.doubleSpinBox__default_cate_item_padding.setProperty("value", 15.0)
        self.doubleSpinBox__default_cate_item_padding.setObjectName("doubleSpinBox__default_cate_item_padding")
        self.horizontalLayout_26.addWidget(self.doubleSpinBox__default_cate_item_padding)
        self.verticalLayout_8.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label__default_record_item_padding = QtWidgets.QLabel(self.tab__padding)
        self.label__default_record_item_padding.setObjectName("label__default_record_item_padding")
        self.horizontalLayout_27.addWidget(self.label__default_record_item_padding)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem11)
        self.doubleSpinBox__default_record_item_padding = QtWidgets.QDoubleSpinBox(self.tab__padding)
        self.doubleSpinBox__default_record_item_padding.setFrame(False)
        self.doubleSpinBox__default_record_item_padding.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__default_record_item_padding.setDecimals(1)
        self.doubleSpinBox__default_record_item_padding.setMinimum(0.0)
        self.doubleSpinBox__default_record_item_padding.setMaximum(100.0)
        self.doubleSpinBox__default_record_item_padding.setSingleStep(0.1)
        self.doubleSpinBox__default_record_item_padding.setProperty("value", 5.0)
        self.doubleSpinBox__default_record_item_padding.setObjectName("doubleSpinBox__default_record_item_padding")
        self.horizontalLayout_27.addWidget(self.doubleSpinBox__default_record_item_padding)
        self.verticalLayout_8.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label__default_inside_item_padding = QtWidgets.QLabel(self.tab__padding)
        self.label__default_inside_item_padding.setObjectName("label__default_inside_item_padding")
        self.horizontalLayout_28.addWidget(self.label__default_inside_item_padding)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem12)
        self.doubleSpinBox__default_inside_item_padding = QtWidgets.QDoubleSpinBox(self.tab__padding)
        self.doubleSpinBox__default_inside_item_padding.setFrame(False)
        self.doubleSpinBox__default_inside_item_padding.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__default_inside_item_padding.setDecimals(1)
        self.doubleSpinBox__default_inside_item_padding.setMinimum(0.0)
        self.doubleSpinBox__default_inside_item_padding.setMaximum(100.0)
        self.doubleSpinBox__default_inside_item_padding.setSingleStep(0.1)
        self.doubleSpinBox__default_inside_item_padding.setProperty("value", 5.0)
        self.doubleSpinBox__default_inside_item_padding.setObjectName("doubleSpinBox__default_inside_item_padding")
        self.horizontalLayout_28.addWidget(self.doubleSpinBox__default_inside_item_padding)
        self.verticalLayout_8.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_32.addLayout(self.verticalLayout_8)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/main/icons/ic_settings_overscan_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab__padding, icon4, "")
        self.tab_text = QtWidgets.QWidget()
        self.tab_text.setObjectName("tab_text")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_text)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox__note = QtWidgets.QGroupBox(self.tab_text)
        self.groupBox__note.setObjectName("groupBox__note")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox__note)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(15)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label__note_font_size = QtWidgets.QLabel(self.groupBox__note)
        self.label__note_font_size.setObjectName("label__note_font_size")
        self.horizontalLayout_18.addWidget(self.label__note_font_size)
        self.spinBox__note_font_size = QtWidgets.QSpinBox(self.groupBox__note)
        self.spinBox__note_font_size.setCursor(QtCore.Qt.PointingHandCursor)
        self.spinBox__note_font_size.setFrame(False)
        self.spinBox__note_font_size.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox__note_font_size.setMinimum(2)
        self.spinBox__note_font_size.setMaximum(50)
        self.spinBox__note_font_size.setProperty("value", 11)
        self.spinBox__note_font_size.setObjectName("spinBox__note_font_size")
        self.horizontalLayout_18.addWidget(self.spinBox__note_font_size)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_18)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem13)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label__note_font_style = QtWidgets.QLabel(self.groupBox__note)
        self.label__note_font_style.setObjectName("label__note_font_style")
        self.horizontalLayout_19.addWidget(self.label__note_font_style)
        self.fontComboBox__note_font_style = QtWidgets.QFontComboBox(self.groupBox__note)
        self.fontComboBox__note_font_style.setCursor(QtCore.Qt.PointingHandCursor)
        self.fontComboBox__note_font_style.setFrame(False)
        self.fontComboBox__note_font_style.setObjectName("fontComboBox__note_font_style")
        self.horizontalLayout_19.addWidget(self.fontComboBox__note_font_style)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_19)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.verticalLayout_7.addWidget(self.groupBox__note)
        self.groupBox__tags = QtWidgets.QGroupBox(self.tab_text)
        self.groupBox__tags.setObjectName("groupBox__tags")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox__tags)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setSpacing(15)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label__tags_font_size = QtWidgets.QLabel(self.groupBox__tags)
        self.label__tags_font_size.setObjectName("label__tags_font_size")
        self.horizontalLayout_21.addWidget(self.label__tags_font_size)
        self.spinBox__tags_font_size = QtWidgets.QSpinBox(self.groupBox__tags)
        self.spinBox__tags_font_size.setCursor(QtCore.Qt.PointingHandCursor)
        self.spinBox__tags_font_size.setFrame(False)
        self.spinBox__tags_font_size.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox__tags_font_size.setMinimum(2)
        self.spinBox__tags_font_size.setMaximum(50)
        self.spinBox__tags_font_size.setProperty("value", 11)
        self.spinBox__tags_font_size.setObjectName("spinBox__tags_font_size")
        self.horizontalLayout_21.addWidget(self.spinBox__tags_font_size)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_21)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem14)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label__tags_font_style = QtWidgets.QLabel(self.groupBox__tags)
        self.label__tags_font_style.setObjectName("label__tags_font_style")
        self.horizontalLayout_22.addWidget(self.label__tags_font_style)
        self.fontComboBox__tags_font_style = QtWidgets.QFontComboBox(self.groupBox__tags)
        self.fontComboBox__tags_font_style.setCursor(QtCore.Qt.PointingHandCursor)
        self.fontComboBox__tags_font_style.setFrame(False)
        self.fontComboBox__tags_font_style.setObjectName("fontComboBox__tags_font_style")
        self.horizontalLayout_22.addWidget(self.fontComboBox__tags_font_style)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_22)
        self.verticalLayout_5.addLayout(self.horizontalLayout_20)
        self.verticalLayout_7.addWidget(self.groupBox__tags)
        self.groupBox__debug = QtWidgets.QGroupBox(self.tab_text)
        self.groupBox__debug.setObjectName("groupBox__debug")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox__debug)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setSpacing(15)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label__debug_font_size = QtWidgets.QLabel(self.groupBox__debug)
        self.label__debug_font_size.setObjectName("label__debug_font_size")
        self.horizontalLayout_24.addWidget(self.label__debug_font_size)
        self.spinBox__debug_font_size = QtWidgets.QSpinBox(self.groupBox__debug)
        self.spinBox__debug_font_size.setCursor(QtCore.Qt.PointingHandCursor)
        self.spinBox__debug_font_size.setFrame(False)
        self.spinBox__debug_font_size.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox__debug_font_size.setMinimum(2)
        self.spinBox__debug_font_size.setMaximum(50)
        self.spinBox__debug_font_size.setProperty("value", 11)
        self.spinBox__debug_font_size.setObjectName("spinBox__debug_font_size")
        self.horizontalLayout_24.addWidget(self.spinBox__debug_font_size)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_24)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem15)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label__debug_font_style = QtWidgets.QLabel(self.groupBox__debug)
        self.label__debug_font_style.setObjectName("label__debug_font_style")
        self.horizontalLayout_25.addWidget(self.label__debug_font_style)
        self.fontComboBox__debug_font_style = QtWidgets.QFontComboBox(self.groupBox__debug)
        self.fontComboBox__debug_font_style.setCursor(QtCore.Qt.PointingHandCursor)
        self.fontComboBox__debug_font_style.setFrame(False)
        self.fontComboBox__debug_font_style.setObjectName("fontComboBox__debug_font_style")
        self.horizontalLayout_25.addWidget(self.fontComboBox__debug_font_style)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_25)
        self.verticalLayout_6.addLayout(self.horizontalLayout_23)
        self.verticalLayout_7.addWidget(self.groupBox__debug)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/main/icons/case_sensitive.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_text, icon5, "")
        self.verticalLayout_10.addWidget(self.tabWidget)
        self.verticalLayout_12.addWidget(self.groupBox__default_icon)
        self.horizontalLayout_34.addLayout(self.verticalLayout_12)
        self.verticalLayout_13.addWidget(self.groupBox__app_properties)
        self.buttonBox__confirm = QtWidgets.QDialogButtonBox(Dialog__preference)
        self.buttonBox__confirm.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox__confirm.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox__confirm.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox__confirm.setObjectName("buttonBox__confirm")
        self.verticalLayout_13.addWidget(self.buttonBox__confirm)

        self.retranslateUi(Dialog__preference)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox__confirm, QtCore.SIGNAL("accepted()"), Dialog__preference.accept)
        QtCore.QObject.connect(self.buttonBox__confirm, QtCore.SIGNAL("rejected()"), Dialog__preference.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog__preference)

    def retranslateUi(self, Dialog__preference):
        Dialog__preference.setWindowTitle(QtWidgets.QApplication.translate("Dialog__preference", "iHDA Preference", None, -1))
        self.groupBox__data.setTitle(QtWidgets.QApplication.translate("Dialog__preference", "Data (Required)", None, -1))
        self.label__data_dirpath.setText(QtWidgets.QApplication.translate("Dialog__preference", "Directory", None, -1))
        self.lineEdit__data_dirpath.setToolTip(QtWidgets.QApplication.translate("Dialog__preference", "Data storage directory", None, -1))
        self.lineEdit__data_dirpath.setPlaceholderText(QtWidgets.QApplication.translate("Dialog__preference", "d:/library", None, -1))
        self.toolButton__select_data_dirpath.setToolTip(QtWidgets.QApplication.translate("Dialog__preference", "Select the directory where data will be saved", None, -1))
        self.toolButton__select_data_dirpath.setStatusTip(QtWidgets.QApplication.translate("Dialog__preference", "Select the directory where data will be saved", None, -1))
        self.label__result_show.setText(QtWidgets.QApplication.translate("Dialog__preference", "Final Path", None, -1))
        self.lineEdit__result.setToolTip(QtWidgets.QApplication.translate("Dialog__preference", "Final data storage directory", None, -1))
        self.label__valid_chk_pixmap.setToolTip(QtWidgets.QApplication.translate("Dialog__preference", "It determines whether it is a valid directory", None, -1))
        self.groupBox__ffmpeg.setTitle(QtWidgets.QApplication.translate("Dialog__preference", "FFmpeg (Optional)", None, -1))
        self.label__ffmpeg_dirpath.setText(QtWidgets.QApplication.translate("Dialog__preference", "Directory", None, -1))
        self.lineEdit__ffmpeg_dirpath.setToolTip(QtWidgets.QApplication.translate("Dialog__preference", "Installed FFmpeg directory", None, -1))
        self.lineEdit__ffmpeg_dirpath.setPlaceholderText(QtWidgets.QApplication.translate("Dialog__preference", "c:/ffmpeg", None, -1))
        self.toolButton__select_ffmpeg_dirpath.setToolTip(QtWidgets.QApplication.translate("Dialog__preference", "Select the directory where FFmpeg is installed", None, -1))
        self.toolButton__select_ffmpeg_dirpath.setStatusTip(QtWidgets.QApplication.translate("Dialog__preference", "Select the directory where FFmpeg is installed", None, -1))
        self.label__ffmpeg_result_show.setText(QtWidgets.QApplication.translate("Dialog__preference", "Final Path", None, -1))
        self.lineEdit__ffmpeg_result.setToolTip(QtWidgets.QApplication.translate("Dialog__preference", "Final installed FFmpeg directory", None, -1))
        self.label__ffmpeg_valid_chk_pixmap.setToolTip(QtWidgets.QApplication.translate("Dialog__preference", "It determines whether it is a valid directory", None, -1))
        self.groupBox__app_properties.setTitle(QtWidgets.QApplication.translate("Dialog__preference", "APP Properties (Default)", None, -1))
        self.pushButton__reset_default_app_properties.setToolTip(QtWidgets.QApplication.translate("Dialog__preference", "Initialize app properties to default values", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("Dialog__preference", "Main View", None, -1))
        self.label__default_main_icon_size.setText(QtWidgets.QApplication.translate("Dialog__preference", "Icon", None, -1))
        self.spinBox__default_main_icon_size.setSuffix(QtWidgets.QApplication.translate("Dialog__preference", "px", None, -1))
        self.groupBox__default_icon.setTitle(QtWidgets.QApplication.translate("Dialog__preference", "Item View", None, -1))
        self.label__view_font_size.setText(QtWidgets.QApplication.translate("Dialog__preference", "Font Size", None, -1))
        self.label__view_font_style.setText(QtWidgets.QApplication.translate("Dialog__preference", "Font Style", None, -1))
        self.label__default_listview_icon_size.setText(QtWidgets.QApplication.translate("Dialog__preference", "ListView", None, -1))
        self.spinBox__default_listview_icon_size.setSuffix(QtWidgets.QApplication.translate("Dialog__preference", "px", None, -1))
        self.label__default_listview_thumb_scale.setText(QtWidgets.QApplication.translate("Dialog__preference", "Thumbnail Scale", None, -1))
        self.doubleSpinBox__default_listview_thumb_scale.setPrefix(QtWidgets.QApplication.translate("Dialog__preference", "x", None, -1))
        self.label__default_tableview_icon_size.setText(QtWidgets.QApplication.translate("Dialog__preference", "TableView", None, -1))
        self.spinBox__default_tableview_icon_size.setSuffix(QtWidgets.QApplication.translate("Dialog__preference", "px", None, -1))
        self.label__default_tableview_thumb_scale.setText(QtWidgets.QApplication.translate("Dialog__preference", "Thumbnail Scale", None, -1))
        self.doubleSpinBox__default_tableview_thumb_scale.setPrefix(QtWidgets.QApplication.translate("Dialog__preference", "x", None, -1))
        self.label__default_treeview_icon_size.setText(QtWidgets.QApplication.translate("Dialog__preference", "TreeView", None, -1))
        self.spinBox__default_treeview_icon_size.setSuffix(QtWidgets.QApplication.translate("Dialog__preference", "px", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab__icon), QtWidgets.QApplication.translate("Dialog__preference", "Icon / Thumbnail", None, -1))
        self.label__default_list_item_padding.setText(QtWidgets.QApplication.translate("Dialog__preference", "List View", None, -1))
        self.doubleSpinBox__default_list_item_padding.setSuffix(QtWidgets.QApplication.translate("Dialog__preference", "px", None, -1))
        self.label__default_table_item_padding.setText(QtWidgets.QApplication.translate("Dialog__preference", "Table View", None, -1))
        self.doubleSpinBox__default_table_item_padding.setSuffix(QtWidgets.QApplication.translate("Dialog__preference", "px", None, -1))
        self.label__default_history_item_padding.setText(QtWidgets.QApplication.translate("Dialog__preference", "History View", None, -1))
        self.doubleSpinBox__default_history_item_padding.setSuffix(QtWidgets.QApplication.translate("Dialog__preference", "px", None, -1))
        self.label__default_cate_item_padding.setText(QtWidgets.QApplication.translate("Dialog__preference", "Category View", None, -1))
        self.doubleSpinBox__default_cate_item_padding.setSuffix(QtWidgets.QApplication.translate("Dialog__preference", "px", None, -1))
        self.label__default_record_item_padding.setText(QtWidgets.QApplication.translate("Dialog__preference", "Record View", None, -1))
        self.doubleSpinBox__default_record_item_padding.setSuffix(QtWidgets.QApplication.translate("Dialog__preference", "px", None, -1))
        self.label__default_inside_item_padding.setText(QtWidgets.QApplication.translate("Dialog__preference", "Inside View", None, -1))
        self.doubleSpinBox__default_inside_item_padding.setSuffix(QtWidgets.QApplication.translate("Dialog__preference", "px", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab__padding), QtWidgets.QApplication.translate("Dialog__preference", "Padding", None, -1))
        self.groupBox__note.setTitle(QtWidgets.QApplication.translate("Dialog__preference", "Note", None, -1))
        self.label__note_font_size.setText(QtWidgets.QApplication.translate("Dialog__preference", "Font Size", None, -1))
        self.label__note_font_style.setText(QtWidgets.QApplication.translate("Dialog__preference", "Font Style", None, -1))
        self.groupBox__tags.setTitle(QtWidgets.QApplication.translate("Dialog__preference", "Tags", None, -1))
        self.label__tags_font_size.setText(QtWidgets.QApplication.translate("Dialog__preference", "Font Size", None, -1))
        self.label__tags_font_style.setText(QtWidgets.QApplication.translate("Dialog__preference", "Font Style", None, -1))
        self.groupBox__debug.setTitle(QtWidgets.QApplication.translate("Dialog__preference", "Debug", None, -1))
        self.label__debug_font_size.setText(QtWidgets.QApplication.translate("Dialog__preference", "Font Size", None, -1))
        self.label__debug_font_style.setText(QtWidgets.QApplication.translate("Dialog__preference", "Font Style", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_text), QtWidgets.QApplication.translate("Dialog__preference", "Text", None, -1))

import preference_icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog__preference = QtWidgets.QDialog()
    ui = Ui_Dialog__preference()
    ui.setupUi(Dialog__preference)
    Dialog__preference.show()
    sys.exit(app.exec_())

