# Generated by pyside6-uic from widgets/preference/preference.ui. Do not edit; regenerate instead.
# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'preference.ui'
##
## Created by: Qt User Interface Compiler version 6.11.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QApplication, QDialog, QDialogButtonBox,
    QDoubleSpinBox, QFontComboBox, QFrame, QGroupBox,
    QHBoxLayout, QLabel, QLineEdit, QPushButton,
    QSizePolicy, QSpacerItem, QSpinBox, QTabWidget,
    QToolButton, QVBoxLayout, QWidget)
from . import preference_icons_rc

class Ui_Dialog__preference(object):
    def setupUi(self, Dialog__preference):
        if not Dialog__preference.objectName():
            Dialog__preference.setObjectName(u"Dialog__preference")
        Dialog__preference.resize(817, 889)
        font = QFont()
        font.setPointSize(11)
        Dialog__preference.setFont(font)
        icon = QIcon()
        icon.addFile(u":/main/icons/viewport_logo_trans.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        Dialog__preference.setWindowIcon(icon)
        Dialog__preference.setLocale(QLocale(QLocale.Language.English, QLocale.Country.UnitedStates))
        self.verticalLayout_13 = QVBoxLayout(Dialog__preference)
        self.verticalLayout_13.setSpacing(5)
        self.verticalLayout_13.setObjectName(u"verticalLayout_13")
        self.verticalLayout_13.setContentsMargins(6, 6, 6, 6)
        self.groupBox__data = QGroupBox(Dialog__preference)
        self.groupBox__data.setObjectName(u"groupBox__data")
        self.horizontalLayout_3 = QHBoxLayout(self.groupBox__data)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.label__pixmap = QLabel(self.groupBox__data)
        self.label__pixmap.setObjectName(u"label__pixmap")
        self.label__pixmap.setMaximumSize(QSize(55, 55))
        self.label__pixmap.setPixmap(QPixmap(u":/main/icons/ic_settings_white.png"))
        self.label__pixmap.setScaledContents(True)
        self.label__pixmap.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_3.addWidget(self.label__pixmap)

        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.label__data_dirpath = QLabel(self.groupBox__data)
        self.label__data_dirpath.setObjectName(u"label__data_dirpath")

        self.horizontalLayout.addWidget(self.label__data_dirpath)

        self.lineEdit__data_dirpath = QLineEdit(self.groupBox__data)
        self.lineEdit__data_dirpath.setObjectName(u"lineEdit__data_dirpath")

        self.horizontalLayout.addWidget(self.lineEdit__data_dirpath)

        self.toolButton__select_data_dirpath = QToolButton(self.groupBox__data)
        self.toolButton__select_data_dirpath.setObjectName(u"toolButton__select_data_dirpath")
        self.toolButton__select_data_dirpath.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon1 = QIcon()
        icon1.addFile(u":/main/icons/ic_folder_white.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButton__select_data_dirpath.setIcon(icon1)
        self.toolButton__select_data_dirpath.setIconSize(QSize(20, 20))

        self.horizontalLayout.addWidget(self.toolButton__select_data_dirpath)


        self.verticalLayout.addLayout(self.horizontalLayout)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.label__result_show = QLabel(self.groupBox__data)
        self.label__result_show.setObjectName(u"label__result_show")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label__result_show.sizePolicy().hasHeightForWidth())
        self.label__result_show.setSizePolicy(sizePolicy)
        self.label__result_show.setFont(font)

        self.horizontalLayout_2.addWidget(self.label__result_show)

        self.lineEdit__result = QLineEdit(self.groupBox__data)
        self.lineEdit__result.setObjectName(u"lineEdit__result")
        self.lineEdit__result.setReadOnly(True)

        self.horizontalLayout_2.addWidget(self.lineEdit__result)

        self.label__valid_chk_pixmap = QLabel(self.groupBox__data)
        self.label__valid_chk_pixmap.setObjectName(u"label__valid_chk_pixmap")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.label__valid_chk_pixmap.sizePolicy().hasHeightForWidth())
        self.label__valid_chk_pixmap.setSizePolicy(sizePolicy1)
        self.label__valid_chk_pixmap.setMaximumSize(QSize(24, 24))
        self.label__valid_chk_pixmap.setPixmap(QPixmap(u":/main/icons/ic_clear_white.png"))
        self.label__valid_chk_pixmap.setScaledContents(True)
        self.label__valid_chk_pixmap.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_2.addWidget(self.label__valid_chk_pixmap)


        self.verticalLayout.addLayout(self.horizontalLayout_2)


        self.horizontalLayout_3.addLayout(self.verticalLayout)


        self.verticalLayout_13.addWidget(self.groupBox__data)

        self.groupBox__ffmpeg = QGroupBox(Dialog__preference)
        self.groupBox__ffmpeg.setObjectName(u"groupBox__ffmpeg")
        self.horizontalLayout_4 = QHBoxLayout(self.groupBox__ffmpeg)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.label__ffmpeg_pixmap = QLabel(self.groupBox__ffmpeg)
        self.label__ffmpeg_pixmap.setObjectName(u"label__ffmpeg_pixmap")
        sizePolicy1.setHeightForWidth(self.label__ffmpeg_pixmap.sizePolicy().hasHeightForWidth())
        self.label__ffmpeg_pixmap.setSizePolicy(sizePolicy1)
        self.label__ffmpeg_pixmap.setMaximumSize(QSize(55, 55))
        self.label__ffmpeg_pixmap.setPixmap(QPixmap(u":/main/icons/ffmpeg.png"))
        self.label__ffmpeg_pixmap.setScaledContents(True)
        self.label__ffmpeg_pixmap.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_4.addWidget(self.label__ffmpeg_pixmap)

        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.label__ffmpeg_dirpath = QLabel(self.groupBox__ffmpeg)
        self.label__ffmpeg_dirpath.setObjectName(u"label__ffmpeg_dirpath")

        self.horizontalLayout_5.addWidget(self.label__ffmpeg_dirpath)

        self.lineEdit__ffmpeg_dirpath = QLineEdit(self.groupBox__ffmpeg)
        self.lineEdit__ffmpeg_dirpath.setObjectName(u"lineEdit__ffmpeg_dirpath")

        self.horizontalLayout_5.addWidget(self.lineEdit__ffmpeg_dirpath)

        self.toolButton__select_ffmpeg_dirpath = QToolButton(self.groupBox__ffmpeg)
        self.toolButton__select_ffmpeg_dirpath.setObjectName(u"toolButton__select_ffmpeg_dirpath")
        self.toolButton__select_ffmpeg_dirpath.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.toolButton__select_ffmpeg_dirpath.setIcon(icon1)
        self.toolButton__select_ffmpeg_dirpath.setIconSize(QSize(20, 20))

        self.horizontalLayout_5.addWidget(self.toolButton__select_ffmpeg_dirpath)


        self.verticalLayout_2.addLayout(self.horizontalLayout_5)

        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.label__ffmpeg_result_show = QLabel(self.groupBox__ffmpeg)
        self.label__ffmpeg_result_show.setObjectName(u"label__ffmpeg_result_show")
        sizePolicy.setHeightForWidth(self.label__ffmpeg_result_show.sizePolicy().hasHeightForWidth())
        self.label__ffmpeg_result_show.setSizePolicy(sizePolicy)
        self.label__ffmpeg_result_show.setFont(font)

        self.horizontalLayout_6.addWidget(self.label__ffmpeg_result_show)

        self.lineEdit__ffmpeg_result = QLineEdit(self.groupBox__ffmpeg)
        self.lineEdit__ffmpeg_result.setObjectName(u"lineEdit__ffmpeg_result")
        self.lineEdit__ffmpeg_result.setReadOnly(True)

        self.horizontalLayout_6.addWidget(self.lineEdit__ffmpeg_result)

        self.label__ffmpeg_valid_chk_pixmap = QLabel(self.groupBox__ffmpeg)
        self.label__ffmpeg_valid_chk_pixmap.setObjectName(u"label__ffmpeg_valid_chk_pixmap")
        sizePolicy1.setHeightForWidth(self.label__ffmpeg_valid_chk_pixmap.sizePolicy().hasHeightForWidth())
        self.label__ffmpeg_valid_chk_pixmap.setSizePolicy(sizePolicy1)
        self.label__ffmpeg_valid_chk_pixmap.setMaximumSize(QSize(24, 24))
        self.label__ffmpeg_valid_chk_pixmap.setPixmap(QPixmap(u":/main/icons/ic_clear_white.png"))
        self.label__ffmpeg_valid_chk_pixmap.setScaledContents(True)
        self.label__ffmpeg_valid_chk_pixmap.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_6.addWidget(self.label__ffmpeg_valid_chk_pixmap)


        self.verticalLayout_2.addLayout(self.horizontalLayout_6)


        self.horizontalLayout_4.addLayout(self.verticalLayout_2)


        self.verticalLayout_13.addWidget(self.groupBox__ffmpeg)

        self.groupBox__app_properties = QGroupBox(Dialog__preference)
        self.groupBox__app_properties.setObjectName(u"groupBox__app_properties")
        self.horizontalLayout_34 = QHBoxLayout(self.groupBox__app_properties)
        self.horizontalLayout_34.setObjectName(u"horizontalLayout_34")
        self.horizontalLayout_34.setContentsMargins(5, 5, 5, 5)
        self.pushButton__reset_default_app_properties = QPushButton(self.groupBox__app_properties)
        self.pushButton__reset_default_app_properties.setObjectName(u"pushButton__reset_default_app_properties")
        self.pushButton__reset_default_app_properties.setMaximumSize(QSize(55, 55))
        self.pushButton__reset_default_app_properties.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon2 = QIcon()
        icon2.addFile(u":/main/icons/ic_refresh_white.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton__reset_default_app_properties.setIcon(icon2)
        self.pushButton__reset_default_app_properties.setIconSize(QSize(50, 50))
        self.pushButton__reset_default_app_properties.setFlat(True)

        self.horizontalLayout_34.addWidget(self.pushButton__reset_default_app_properties)

        self.verticalLayout_12 = QVBoxLayout()
        self.verticalLayout_12.setObjectName(u"verticalLayout_12")
        self.groupBox = QGroupBox(self.groupBox__app_properties)
        self.groupBox.setObjectName(u"groupBox")
        self.verticalLayout_11 = QVBoxLayout(self.groupBox)
        self.verticalLayout_11.setObjectName(u"verticalLayout_11")
        self.horizontalLayout_33 = QHBoxLayout()
        self.horizontalLayout_33.setObjectName(u"horizontalLayout_33")
        self.label__default_main_icon_size = QLabel(self.groupBox)
        self.label__default_main_icon_size.setObjectName(u"label__default_main_icon_size")

        self.horizontalLayout_33.addWidget(self.label__default_main_icon_size)

        self.spinBox__default_main_icon_size = QSpinBox(self.groupBox)
        self.spinBox__default_main_icon_size.setObjectName(u"spinBox__default_main_icon_size")
        self.spinBox__default_main_icon_size.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.spinBox__default_main_icon_size.setFrame(False)
        self.spinBox__default_main_icon_size.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spinBox__default_main_icon_size.setMinimum(1)
        self.spinBox__default_main_icon_size.setMaximum(30)
        self.spinBox__default_main_icon_size.setValue(20)

        self.horizontalLayout_33.addWidget(self.spinBox__default_main_icon_size)


        self.verticalLayout_11.addLayout(self.horizontalLayout_33)


        self.verticalLayout_12.addWidget(self.groupBox)

        self.groupBox__default_icon = QGroupBox(self.groupBox__app_properties)
        self.groupBox__default_icon.setObjectName(u"groupBox__default_icon")
        self.verticalLayout_10 = QVBoxLayout(self.groupBox__default_icon)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_10 = QHBoxLayout()
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.label__view_font_size = QLabel(self.groupBox__default_icon)
        self.label__view_font_size.setObjectName(u"label__view_font_size")

        self.horizontalLayout_10.addWidget(self.label__view_font_size)

        self.spinBox__view_font_size = QSpinBox(self.groupBox__default_icon)
        self.spinBox__view_font_size.setObjectName(u"spinBox__view_font_size")
        self.spinBox__view_font_size.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.spinBox__view_font_size.setFrame(False)
        self.spinBox__view_font_size.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spinBox__view_font_size.setMinimum(2)
        self.spinBox__view_font_size.setMaximum(50)
        self.spinBox__view_font_size.setValue(11)

        self.horizontalLayout_10.addWidget(self.spinBox__view_font_size)


        self.horizontalLayout_7.addLayout(self.horizontalLayout_10)

        self.horizontalSpacer_4 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_7.addItem(self.horizontalSpacer_4)

        self.horizontalLayout_8 = QHBoxLayout()
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.label__view_font_style = QLabel(self.groupBox__default_icon)
        self.label__view_font_style.setObjectName(u"label__view_font_style")

        self.horizontalLayout_8.addWidget(self.label__view_font_style)

        self.fontComboBox__view_font_style = QFontComboBox(self.groupBox__default_icon)
        self.fontComboBox__view_font_style.setObjectName(u"fontComboBox__view_font_style")
        self.fontComboBox__view_font_style.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.fontComboBox__view_font_style.setFrame(False)

        self.horizontalLayout_8.addWidget(self.fontComboBox__view_font_style)


        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)


        self.verticalLayout_10.addLayout(self.horizontalLayout_7)

        self.line = QFrame(self.groupBox__default_icon)
        self.line.setObjectName(u"line")
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)

        self.verticalLayout_10.addWidget(self.line)

        self.tabWidget = QTabWidget(self.groupBox__default_icon)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setIconSize(QSize(20, 20))
        self.tab__icon = QWidget()
        self.tab__icon.setObjectName(u"tab__icon")
        self.verticalLayout_3 = QVBoxLayout(self.tab__icon)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_14 = QHBoxLayout()
        self.horizontalLayout_14.setSpacing(15)
        self.horizontalLayout_14.setObjectName(u"horizontalLayout_14")
        self.horizontalLayout_11 = QHBoxLayout()
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.label__default_listview_icon_size = QLabel(self.tab__icon)
        self.label__default_listview_icon_size.setObjectName(u"label__default_listview_icon_size")

        self.horizontalLayout_11.addWidget(self.label__default_listview_icon_size)

        self.spinBox__default_listview_icon_size = QSpinBox(self.tab__icon)
        self.spinBox__default_listview_icon_size.setObjectName(u"spinBox__default_listview_icon_size")
        self.spinBox__default_listview_icon_size.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.spinBox__default_listview_icon_size.setFrame(False)
        self.spinBox__default_listview_icon_size.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spinBox__default_listview_icon_size.setMinimum(1)
        self.spinBox__default_listview_icon_size.setValue(38)

        self.horizontalLayout_11.addWidget(self.spinBox__default_listview_icon_size)


        self.horizontalLayout_14.addLayout(self.horizontalLayout_11)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_14.addItem(self.horizontalSpacer)

        self.horizontalLayout_13 = QHBoxLayout()
        self.horizontalLayout_13.setObjectName(u"horizontalLayout_13")
        self.label__default_listview_thumb_scale = QLabel(self.tab__icon)
        self.label__default_listview_thumb_scale.setObjectName(u"label__default_listview_thumb_scale")

        self.horizontalLayout_13.addWidget(self.label__default_listview_thumb_scale)

        self.doubleSpinBox__default_listview_thumb_scale = QDoubleSpinBox(self.tab__icon)
        self.doubleSpinBox__default_listview_thumb_scale.setObjectName(u"doubleSpinBox__default_listview_thumb_scale")
        self.doubleSpinBox__default_listview_thumb_scale.setFrame(False)
        self.doubleSpinBox__default_listview_thumb_scale.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.doubleSpinBox__default_listview_thumb_scale.setDecimals(1)
        self.doubleSpinBox__default_listview_thumb_scale.setMinimum(0.100000000000000)
        self.doubleSpinBox__default_listview_thumb_scale.setMaximum(50.000000000000000)
        self.doubleSpinBox__default_listview_thumb_scale.setSingleStep(0.100000000000000)
        self.doubleSpinBox__default_listview_thumb_scale.setValue(2.000000000000000)

        self.horizontalLayout_13.addWidget(self.doubleSpinBox__default_listview_thumb_scale)

        self.horizontalSpacer_14 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_13.addItem(self.horizontalSpacer_14)


        self.horizontalLayout_14.addLayout(self.horizontalLayout_13)


        self.verticalLayout_3.addLayout(self.horizontalLayout_14)

        self.horizontalLayout_16 = QHBoxLayout()
        self.horizontalLayout_16.setSpacing(15)
        self.horizontalLayout_16.setObjectName(u"horizontalLayout_16")
        self.horizontalLayout_12 = QHBoxLayout()
        self.horizontalLayout_12.setObjectName(u"horizontalLayout_12")
        self.label__default_tableview_icon_size = QLabel(self.tab__icon)
        self.label__default_tableview_icon_size.setObjectName(u"label__default_tableview_icon_size")

        self.horizontalLayout_12.addWidget(self.label__default_tableview_icon_size)

        self.spinBox__default_tableview_icon_size = QSpinBox(self.tab__icon)
        self.spinBox__default_tableview_icon_size.setObjectName(u"spinBox__default_tableview_icon_size")
        self.spinBox__default_tableview_icon_size.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.spinBox__default_tableview_icon_size.setFrame(False)
        self.spinBox__default_tableview_icon_size.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spinBox__default_tableview_icon_size.setMinimum(1)
        self.spinBox__default_tableview_icon_size.setValue(38)

        self.horizontalLayout_12.addWidget(self.spinBox__default_tableview_icon_size)


        self.horizontalLayout_16.addLayout(self.horizontalLayout_12)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_16.addItem(self.horizontalSpacer_2)

        self.horizontalLayout_15 = QHBoxLayout()
        self.horizontalLayout_15.setObjectName(u"horizontalLayout_15")
        self.label__default_tableview_thumb_scale = QLabel(self.tab__icon)
        self.label__default_tableview_thumb_scale.setObjectName(u"label__default_tableview_thumb_scale")

        self.horizontalLayout_15.addWidget(self.label__default_tableview_thumb_scale)

        self.doubleSpinBox__default_tableview_thumb_scale = QDoubleSpinBox(self.tab__icon)
        self.doubleSpinBox__default_tableview_thumb_scale.setObjectName(u"doubleSpinBox__default_tableview_thumb_scale")
        self.doubleSpinBox__default_tableview_thumb_scale.setFrame(False)
        self.doubleSpinBox__default_tableview_thumb_scale.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.doubleSpinBox__default_tableview_thumb_scale.setDecimals(1)
        self.doubleSpinBox__default_tableview_thumb_scale.setMinimum(0.100000000000000)
        self.doubleSpinBox__default_tableview_thumb_scale.setMaximum(50.000000000000000)
        self.doubleSpinBox__default_tableview_thumb_scale.setSingleStep(0.100000000000000)
        self.doubleSpinBox__default_tableview_thumb_scale.setValue(1.300000000000000)

        self.horizontalLayout_15.addWidget(self.doubleSpinBox__default_tableview_thumb_scale)

        self.horizontalSpacer_15 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_15.addItem(self.horizontalSpacer_15)


        self.horizontalLayout_16.addLayout(self.horizontalLayout_15)


        self.verticalLayout_3.addLayout(self.horizontalLayout_16)

        self.horizontalLayout_9 = QHBoxLayout()
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.label__default_treeview_icon_size = QLabel(self.tab__icon)
        self.label__default_treeview_icon_size.setObjectName(u"label__default_treeview_icon_size")

        self.horizontalLayout_9.addWidget(self.label__default_treeview_icon_size)

        self.spinBox__default_treeview_icon_size = QSpinBox(self.tab__icon)
        self.spinBox__default_treeview_icon_size.setObjectName(u"spinBox__default_treeview_icon_size")
        self.spinBox__default_treeview_icon_size.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.spinBox__default_treeview_icon_size.setFrame(False)
        self.spinBox__default_treeview_icon_size.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spinBox__default_treeview_icon_size.setMinimum(1)
        self.spinBox__default_treeview_icon_size.setValue(24)

        self.horizontalLayout_9.addWidget(self.spinBox__default_treeview_icon_size)

        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_9.addItem(self.horizontalSpacer_3)


        self.verticalLayout_3.addLayout(self.horizontalLayout_9)

        icon3 = QIcon()
        icon3.addFile(u":/main/icons/ic_photo_white.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.tabWidget.addTab(self.tab__icon, icon3, "")
        self.tab__padding = QWidget()
        self.tab__padding.setObjectName(u"tab__padding")
        self.horizontalLayout_32 = QHBoxLayout(self.tab__padding)
        self.horizontalLayout_32.setSpacing(5)
        self.horizontalLayout_32.setObjectName(u"horizontalLayout_32")
        self.horizontalLayout_32.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_9 = QVBoxLayout()
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.horizontalLayout_29 = QHBoxLayout()
        self.horizontalLayout_29.setObjectName(u"horizontalLayout_29")
        self.label__default_list_item_padding = QLabel(self.tab__padding)
        self.label__default_list_item_padding.setObjectName(u"label__default_list_item_padding")

        self.horizontalLayout_29.addWidget(self.label__default_list_item_padding)

        self.horizontalSpacer_11 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_29.addItem(self.horizontalSpacer_11)

        self.doubleSpinBox__default_list_item_padding = QDoubleSpinBox(self.tab__padding)
        self.doubleSpinBox__default_list_item_padding.setObjectName(u"doubleSpinBox__default_list_item_padding")
        self.doubleSpinBox__default_list_item_padding.setFrame(False)
        self.doubleSpinBox__default_list_item_padding.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.doubleSpinBox__default_list_item_padding.setDecimals(1)
        self.doubleSpinBox__default_list_item_padding.setMinimum(0.000000000000000)
        self.doubleSpinBox__default_list_item_padding.setMaximum(100.000000000000000)
        self.doubleSpinBox__default_list_item_padding.setSingleStep(0.100000000000000)
        self.doubleSpinBox__default_list_item_padding.setValue(20.000000000000000)

        self.horizontalLayout_29.addWidget(self.doubleSpinBox__default_list_item_padding)


        self.verticalLayout_9.addLayout(self.horizontalLayout_29)

        self.horizontalLayout_30 = QHBoxLayout()
        self.horizontalLayout_30.setObjectName(u"horizontalLayout_30")
        self.label__default_table_item_padding = QLabel(self.tab__padding)
        self.label__default_table_item_padding.setObjectName(u"label__default_table_item_padding")

        self.horizontalLayout_30.addWidget(self.label__default_table_item_padding)

        self.horizontalSpacer_12 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_30.addItem(self.horizontalSpacer_12)

        self.doubleSpinBox__default_table_item_padding = QDoubleSpinBox(self.tab__padding)
        self.doubleSpinBox__default_table_item_padding.setObjectName(u"doubleSpinBox__default_table_item_padding")
        self.doubleSpinBox__default_table_item_padding.setFrame(False)
        self.doubleSpinBox__default_table_item_padding.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.doubleSpinBox__default_table_item_padding.setDecimals(1)
        self.doubleSpinBox__default_table_item_padding.setMinimum(0.000000000000000)
        self.doubleSpinBox__default_table_item_padding.setMaximum(100.000000000000000)
        self.doubleSpinBox__default_table_item_padding.setSingleStep(0.100000000000000)
        self.doubleSpinBox__default_table_item_padding.setValue(0.000000000000000)

        self.horizontalLayout_30.addWidget(self.doubleSpinBox__default_table_item_padding)


        self.verticalLayout_9.addLayout(self.horizontalLayout_30)

        self.horizontalLayout_31 = QHBoxLayout()
        self.horizontalLayout_31.setObjectName(u"horizontalLayout_31")
        self.label__default_history_item_padding = QLabel(self.tab__padding)
        self.label__default_history_item_padding.setObjectName(u"label__default_history_item_padding")

        self.horizontalLayout_31.addWidget(self.label__default_history_item_padding)

        self.horizontalSpacer_13 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_31.addItem(self.horizontalSpacer_13)

        self.doubleSpinBox__default_history_item_padding = QDoubleSpinBox(self.tab__padding)
        self.doubleSpinBox__default_history_item_padding.setObjectName(u"doubleSpinBox__default_history_item_padding")
        self.doubleSpinBox__default_history_item_padding.setFrame(False)
        self.doubleSpinBox__default_history_item_padding.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.doubleSpinBox__default_history_item_padding.setDecimals(1)
        self.doubleSpinBox__default_history_item_padding.setMinimum(0.000000000000000)
        self.doubleSpinBox__default_history_item_padding.setMaximum(100.000000000000000)
        self.doubleSpinBox__default_history_item_padding.setSingleStep(0.100000000000000)
        self.doubleSpinBox__default_history_item_padding.setValue(0.000000000000000)

        self.horizontalLayout_31.addWidget(self.doubleSpinBox__default_history_item_padding)


        self.verticalLayout_9.addLayout(self.horizontalLayout_31)


        self.horizontalLayout_32.addLayout(self.verticalLayout_9)

        self.horizontalSpacer_16 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_32.addItem(self.horizontalSpacer_16)

        self.verticalLayout_8 = QVBoxLayout()
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.horizontalLayout_26 = QHBoxLayout()
        self.horizontalLayout_26.setObjectName(u"horizontalLayout_26")
        self.label__default_cate_item_padding = QLabel(self.tab__padding)
        self.label__default_cate_item_padding.setObjectName(u"label__default_cate_item_padding")

        self.horizontalLayout_26.addWidget(self.label__default_cate_item_padding)

        self.horizontalSpacer_8 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_26.addItem(self.horizontalSpacer_8)

        self.doubleSpinBox__default_cate_item_padding = QDoubleSpinBox(self.tab__padding)
        self.doubleSpinBox__default_cate_item_padding.setObjectName(u"doubleSpinBox__default_cate_item_padding")
        self.doubleSpinBox__default_cate_item_padding.setFrame(False)
        self.doubleSpinBox__default_cate_item_padding.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.doubleSpinBox__default_cate_item_padding.setDecimals(1)
        self.doubleSpinBox__default_cate_item_padding.setMinimum(0.000000000000000)
        self.doubleSpinBox__default_cate_item_padding.setMaximum(100.000000000000000)
        self.doubleSpinBox__default_cate_item_padding.setSingleStep(0.100000000000000)
        self.doubleSpinBox__default_cate_item_padding.setValue(15.000000000000000)

        self.horizontalLayout_26.addWidget(self.doubleSpinBox__default_cate_item_padding)


        self.verticalLayout_8.addLayout(self.horizontalLayout_26)

        self.horizontalLayout_27 = QHBoxLayout()
        self.horizontalLayout_27.setObjectName(u"horizontalLayout_27")
        self.label__default_record_item_padding = QLabel(self.tab__padding)
        self.label__default_record_item_padding.setObjectName(u"label__default_record_item_padding")

        self.horizontalLayout_27.addWidget(self.label__default_record_item_padding)

        self.horizontalSpacer_9 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_27.addItem(self.horizontalSpacer_9)

        self.doubleSpinBox__default_record_item_padding = QDoubleSpinBox(self.tab__padding)
        self.doubleSpinBox__default_record_item_padding.setObjectName(u"doubleSpinBox__default_record_item_padding")
        self.doubleSpinBox__default_record_item_padding.setFrame(False)
        self.doubleSpinBox__default_record_item_padding.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.doubleSpinBox__default_record_item_padding.setDecimals(1)
        self.doubleSpinBox__default_record_item_padding.setMinimum(0.000000000000000)
        self.doubleSpinBox__default_record_item_padding.setMaximum(100.000000000000000)
        self.doubleSpinBox__default_record_item_padding.setSingleStep(0.100000000000000)
        self.doubleSpinBox__default_record_item_padding.setValue(5.000000000000000)

        self.horizontalLayout_27.addWidget(self.doubleSpinBox__default_record_item_padding)


        self.verticalLayout_8.addLayout(self.horizontalLayout_27)

        self.horizontalLayout_28 = QHBoxLayout()
        self.horizontalLayout_28.setObjectName(u"horizontalLayout_28")
        self.label__default_inside_item_padding = QLabel(self.tab__padding)
        self.label__default_inside_item_padding.setObjectName(u"label__default_inside_item_padding")

        self.horizontalLayout_28.addWidget(self.label__default_inside_item_padding)

        self.horizontalSpacer_10 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_28.addItem(self.horizontalSpacer_10)

        self.doubleSpinBox__default_inside_item_padding = QDoubleSpinBox(self.tab__padding)
        self.doubleSpinBox__default_inside_item_padding.setObjectName(u"doubleSpinBox__default_inside_item_padding")
        self.doubleSpinBox__default_inside_item_padding.setFrame(False)
        self.doubleSpinBox__default_inside_item_padding.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.doubleSpinBox__default_inside_item_padding.setDecimals(1)
        self.doubleSpinBox__default_inside_item_padding.setMinimum(0.000000000000000)
        self.doubleSpinBox__default_inside_item_padding.setMaximum(100.000000000000000)
        self.doubleSpinBox__default_inside_item_padding.setSingleStep(0.100000000000000)
        self.doubleSpinBox__default_inside_item_padding.setValue(5.000000000000000)

        self.horizontalLayout_28.addWidget(self.doubleSpinBox__default_inside_item_padding)


        self.verticalLayout_8.addLayout(self.horizontalLayout_28)


        self.horizontalLayout_32.addLayout(self.verticalLayout_8)

        icon4 = QIcon()
        icon4.addFile(u":/main/icons/ic_settings_overscan_white.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.tabWidget.addTab(self.tab__padding, icon4, "")
        self.tab_text = QWidget()
        self.tab_text.setObjectName(u"tab_text")
        self.verticalLayout_7 = QVBoxLayout(self.tab_text)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.groupBox__note = QGroupBox(self.tab_text)
        self.groupBox__note.setObjectName(u"groupBox__note")
        self.verticalLayout_4 = QVBoxLayout(self.groupBox__note)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.horizontalLayout_17 = QHBoxLayout()
        self.horizontalLayout_17.setSpacing(15)
        self.horizontalLayout_17.setObjectName(u"horizontalLayout_17")
        self.horizontalLayout_18 = QHBoxLayout()
        self.horizontalLayout_18.setObjectName(u"horizontalLayout_18")
        self.label__note_font_size = QLabel(self.groupBox__note)
        self.label__note_font_size.setObjectName(u"label__note_font_size")

        self.horizontalLayout_18.addWidget(self.label__note_font_size)

        self.spinBox__note_font_size = QSpinBox(self.groupBox__note)
        self.spinBox__note_font_size.setObjectName(u"spinBox__note_font_size")
        self.spinBox__note_font_size.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.spinBox__note_font_size.setFrame(False)
        self.spinBox__note_font_size.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spinBox__note_font_size.setMinimum(2)
        self.spinBox__note_font_size.setMaximum(50)
        self.spinBox__note_font_size.setValue(11)

        self.horizontalLayout_18.addWidget(self.spinBox__note_font_size)


        self.horizontalLayout_17.addLayout(self.horizontalLayout_18)

        self.horizontalSpacer_5 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_17.addItem(self.horizontalSpacer_5)

        self.horizontalLayout_19 = QHBoxLayout()
        self.horizontalLayout_19.setObjectName(u"horizontalLayout_19")
        self.label__note_font_style = QLabel(self.groupBox__note)
        self.label__note_font_style.setObjectName(u"label__note_font_style")

        self.horizontalLayout_19.addWidget(self.label__note_font_style)

        self.fontComboBox__note_font_style = QFontComboBox(self.groupBox__note)
        self.fontComboBox__note_font_style.setObjectName(u"fontComboBox__note_font_style")
        self.fontComboBox__note_font_style.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.fontComboBox__note_font_style.setFrame(False)

        self.horizontalLayout_19.addWidget(self.fontComboBox__note_font_style)


        self.horizontalLayout_17.addLayout(self.horizontalLayout_19)


        self.verticalLayout_4.addLayout(self.horizontalLayout_17)


        self.verticalLayout_7.addWidget(self.groupBox__note)

        self.groupBox__tags = QGroupBox(self.tab_text)
        self.groupBox__tags.setObjectName(u"groupBox__tags")
        self.verticalLayout_5 = QVBoxLayout(self.groupBox__tags)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.horizontalLayout_20 = QHBoxLayout()
        self.horizontalLayout_20.setSpacing(15)
        self.horizontalLayout_20.setObjectName(u"horizontalLayout_20")
        self.horizontalLayout_21 = QHBoxLayout()
        self.horizontalLayout_21.setObjectName(u"horizontalLayout_21")
        self.label__tags_font_size = QLabel(self.groupBox__tags)
        self.label__tags_font_size.setObjectName(u"label__tags_font_size")

        self.horizontalLayout_21.addWidget(self.label__tags_font_size)

        self.spinBox__tags_font_size = QSpinBox(self.groupBox__tags)
        self.spinBox__tags_font_size.setObjectName(u"spinBox__tags_font_size")
        self.spinBox__tags_font_size.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.spinBox__tags_font_size.setFrame(False)
        self.spinBox__tags_font_size.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spinBox__tags_font_size.setMinimum(2)
        self.spinBox__tags_font_size.setMaximum(50)
        self.spinBox__tags_font_size.setValue(11)

        self.horizontalLayout_21.addWidget(self.spinBox__tags_font_size)


        self.horizontalLayout_20.addLayout(self.horizontalLayout_21)

        self.horizontalSpacer_6 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_20.addItem(self.horizontalSpacer_6)

        self.horizontalLayout_22 = QHBoxLayout()
        self.horizontalLayout_22.setObjectName(u"horizontalLayout_22")
        self.label__tags_font_style = QLabel(self.groupBox__tags)
        self.label__tags_font_style.setObjectName(u"label__tags_font_style")

        self.horizontalLayout_22.addWidget(self.label__tags_font_style)

        self.fontComboBox__tags_font_style = QFontComboBox(self.groupBox__tags)
        self.fontComboBox__tags_font_style.setObjectName(u"fontComboBox__tags_font_style")
        self.fontComboBox__tags_font_style.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.fontComboBox__tags_font_style.setFrame(False)

        self.horizontalLayout_22.addWidget(self.fontComboBox__tags_font_style)


        self.horizontalLayout_20.addLayout(self.horizontalLayout_22)


        self.verticalLayout_5.addLayout(self.horizontalLayout_20)


        self.verticalLayout_7.addWidget(self.groupBox__tags)

        self.groupBox__debug = QGroupBox(self.tab_text)
        self.groupBox__debug.setObjectName(u"groupBox__debug")
        self.verticalLayout_6 = QVBoxLayout(self.groupBox__debug)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.horizontalLayout_23 = QHBoxLayout()
        self.horizontalLayout_23.setSpacing(15)
        self.horizontalLayout_23.setObjectName(u"horizontalLayout_23")
        self.horizontalLayout_24 = QHBoxLayout()
        self.horizontalLayout_24.setObjectName(u"horizontalLayout_24")
        self.label__debug_font_size = QLabel(self.groupBox__debug)
        self.label__debug_font_size.setObjectName(u"label__debug_font_size")

        self.horizontalLayout_24.addWidget(self.label__debug_font_size)

        self.spinBox__debug_font_size = QSpinBox(self.groupBox__debug)
        self.spinBox__debug_font_size.setObjectName(u"spinBox__debug_font_size")
        self.spinBox__debug_font_size.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.spinBox__debug_font_size.setFrame(False)
        self.spinBox__debug_font_size.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spinBox__debug_font_size.setMinimum(2)
        self.spinBox__debug_font_size.setMaximum(50)
        self.spinBox__debug_font_size.setValue(11)

        self.horizontalLayout_24.addWidget(self.spinBox__debug_font_size)


        self.horizontalLayout_23.addLayout(self.horizontalLayout_24)

        self.horizontalSpacer_7 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_23.addItem(self.horizontalSpacer_7)

        self.horizontalLayout_25 = QHBoxLayout()
        self.horizontalLayout_25.setObjectName(u"horizontalLayout_25")
        self.label__debug_font_style = QLabel(self.groupBox__debug)
        self.label__debug_font_style.setObjectName(u"label__debug_font_style")

        self.horizontalLayout_25.addWidget(self.label__debug_font_style)

        self.fontComboBox__debug_font_style = QFontComboBox(self.groupBox__debug)
        self.fontComboBox__debug_font_style.setObjectName(u"fontComboBox__debug_font_style")
        self.fontComboBox__debug_font_style.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.fontComboBox__debug_font_style.setFrame(False)

        self.horizontalLayout_25.addWidget(self.fontComboBox__debug_font_style)


        self.horizontalLayout_23.addLayout(self.horizontalLayout_25)


        self.verticalLayout_6.addLayout(self.horizontalLayout_23)


        self.verticalLayout_7.addWidget(self.groupBox__debug)

        icon5 = QIcon()
        icon5.addFile(u":/main/icons/case_sensitive.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.tabWidget.addTab(self.tab_text, icon5, "")

        self.verticalLayout_10.addWidget(self.tabWidget)


        self.verticalLayout_12.addWidget(self.groupBox__default_icon)


        self.horizontalLayout_34.addLayout(self.verticalLayout_12)


        self.verticalLayout_13.addWidget(self.groupBox__app_properties)

        self.buttonBox__confirm = QDialogButtonBox(Dialog__preference)
        self.buttonBox__confirm.setObjectName(u"buttonBox__confirm")
        self.buttonBox__confirm.setLocale(QLocale(QLocale.Language.English, QLocale.Country.UnitedStates))
        self.buttonBox__confirm.setOrientation(Qt.Orientation.Horizontal)
        self.buttonBox__confirm.setStandardButtons(QDialogButtonBox.StandardButton.Cancel|QDialogButtonBox.StandardButton.Ok)

        self.verticalLayout_13.addWidget(self.buttonBox__confirm)


        self.retranslateUi(Dialog__preference)
        self.buttonBox__confirm.accepted.connect(Dialog__preference.accept)
        self.buttonBox__confirm.rejected.connect(Dialog__preference.reject)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Dialog__preference)
    # setupUi

    def retranslateUi(self, Dialog__preference):
        Dialog__preference.setWindowTitle(QCoreApplication.translate("Dialog__preference", u"iHDA Preference", None))
        self.groupBox__data.setTitle(QCoreApplication.translate("Dialog__preference", u"Data (Required)", None))
        self.label__pixmap.setText("")
        self.label__data_dirpath.setText(QCoreApplication.translate("Dialog__preference", u"Directory", None))
#if QT_CONFIG(tooltip)
        self.lineEdit__data_dirpath.setToolTip(QCoreApplication.translate("Dialog__preference", u"Data storage directory", None))
#endif // QT_CONFIG(tooltip)
        self.lineEdit__data_dirpath.setPlaceholderText(QCoreApplication.translate("Dialog__preference", u"d:/library", None))
#if QT_CONFIG(tooltip)
        self.toolButton__select_data_dirpath.setToolTip(QCoreApplication.translate("Dialog__preference", u"Select the directory where data will be saved", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.toolButton__select_data_dirpath.setStatusTip(QCoreApplication.translate("Dialog__preference", u"Select the directory where data will be saved", None))
#endif // QT_CONFIG(statustip)
        self.toolButton__select_data_dirpath.setText("")
        self.label__result_show.setText(QCoreApplication.translate("Dialog__preference", u"Final Path", None))
#if QT_CONFIG(tooltip)
        self.lineEdit__result.setToolTip(QCoreApplication.translate("Dialog__preference", u"Final data storage directory", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label__valid_chk_pixmap.setToolTip(QCoreApplication.translate("Dialog__preference", u"It determines whether it is a valid directory", None))
#endif // QT_CONFIG(tooltip)
        self.label__valid_chk_pixmap.setText("")
        self.groupBox__ffmpeg.setTitle(QCoreApplication.translate("Dialog__preference", u"FFmpeg (Optional)", None))
        self.label__ffmpeg_pixmap.setText("")
        self.label__ffmpeg_dirpath.setText(QCoreApplication.translate("Dialog__preference", u"Directory", None))
#if QT_CONFIG(tooltip)
        self.lineEdit__ffmpeg_dirpath.setToolTip(QCoreApplication.translate("Dialog__preference", u"Installed FFmpeg directory", None))
#endif // QT_CONFIG(tooltip)
        self.lineEdit__ffmpeg_dirpath.setPlaceholderText(QCoreApplication.translate("Dialog__preference", u"c:/ffmpeg", None))
#if QT_CONFIG(tooltip)
        self.toolButton__select_ffmpeg_dirpath.setToolTip(QCoreApplication.translate("Dialog__preference", u"Select the directory where FFmpeg is installed", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.toolButton__select_ffmpeg_dirpath.setStatusTip(QCoreApplication.translate("Dialog__preference", u"Select the directory where FFmpeg is installed", None))
#endif // QT_CONFIG(statustip)
        self.toolButton__select_ffmpeg_dirpath.setText("")
        self.label__ffmpeg_result_show.setText(QCoreApplication.translate("Dialog__preference", u"Final Path", None))
#if QT_CONFIG(tooltip)
        self.lineEdit__ffmpeg_result.setToolTip(QCoreApplication.translate("Dialog__preference", u"Final installed FFmpeg directory", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label__ffmpeg_valid_chk_pixmap.setToolTip(QCoreApplication.translate("Dialog__preference", u"It determines whether it is a valid directory", None))
#endif // QT_CONFIG(tooltip)
        self.label__ffmpeg_valid_chk_pixmap.setText("")
        self.groupBox__app_properties.setTitle(QCoreApplication.translate("Dialog__preference", u"APP Properties (Default)", None))
#if QT_CONFIG(tooltip)
        self.pushButton__reset_default_app_properties.setToolTip(QCoreApplication.translate("Dialog__preference", u"Initialize app properties to default values", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton__reset_default_app_properties.setText("")
        self.groupBox.setTitle(QCoreApplication.translate("Dialog__preference", u"Main View", None))
        self.label__default_main_icon_size.setText(QCoreApplication.translate("Dialog__preference", u"Icon", None))
        self.spinBox__default_main_icon_size.setSuffix(QCoreApplication.translate("Dialog__preference", u"px", None))
        self.groupBox__default_icon.setTitle(QCoreApplication.translate("Dialog__preference", u"Item View", None))
        self.label__view_font_size.setText(QCoreApplication.translate("Dialog__preference", u"Font Size", None))
        self.label__view_font_style.setText(QCoreApplication.translate("Dialog__preference", u"Font Style", None))
        self.label__default_listview_icon_size.setText(QCoreApplication.translate("Dialog__preference", u"ListView", None))
        self.spinBox__default_listview_icon_size.setSuffix(QCoreApplication.translate("Dialog__preference", u"px", None))
        self.label__default_listview_thumb_scale.setText(QCoreApplication.translate("Dialog__preference", u"Thumbnail Scale", None))
        self.doubleSpinBox__default_listview_thumb_scale.setPrefix(QCoreApplication.translate("Dialog__preference", u"x", None))
        self.label__default_tableview_icon_size.setText(QCoreApplication.translate("Dialog__preference", u"TableView", None))
        self.spinBox__default_tableview_icon_size.setSuffix(QCoreApplication.translate("Dialog__preference", u"px", None))
        self.label__default_tableview_thumb_scale.setText(QCoreApplication.translate("Dialog__preference", u"Thumbnail Scale", None))
        self.doubleSpinBox__default_tableview_thumb_scale.setPrefix(QCoreApplication.translate("Dialog__preference", u"x", None))
        self.label__default_treeview_icon_size.setText(QCoreApplication.translate("Dialog__preference", u"TreeView", None))
        self.spinBox__default_treeview_icon_size.setSuffix(QCoreApplication.translate("Dialog__preference", u"px", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab__icon), QCoreApplication.translate("Dialog__preference", u"Icon / Thumbnail", None))
        self.label__default_list_item_padding.setText(QCoreApplication.translate("Dialog__preference", u"List View", None))
        self.doubleSpinBox__default_list_item_padding.setSuffix(QCoreApplication.translate("Dialog__preference", u"px", None))
        self.label__default_table_item_padding.setText(QCoreApplication.translate("Dialog__preference", u"Table View", None))
        self.doubleSpinBox__default_table_item_padding.setSuffix(QCoreApplication.translate("Dialog__preference", u"px", None))
        self.label__default_history_item_padding.setText(QCoreApplication.translate("Dialog__preference", u"History View", None))
        self.doubleSpinBox__default_history_item_padding.setSuffix(QCoreApplication.translate("Dialog__preference", u"px", None))
        self.label__default_cate_item_padding.setText(QCoreApplication.translate("Dialog__preference", u"Category View", None))
        self.doubleSpinBox__default_cate_item_padding.setSuffix(QCoreApplication.translate("Dialog__preference", u"px", None))
        self.label__default_record_item_padding.setText(QCoreApplication.translate("Dialog__preference", u"Record View", None))
        self.doubleSpinBox__default_record_item_padding.setSuffix(QCoreApplication.translate("Dialog__preference", u"px", None))
        self.label__default_inside_item_padding.setText(QCoreApplication.translate("Dialog__preference", u"Inside View", None))
        self.doubleSpinBox__default_inside_item_padding.setSuffix(QCoreApplication.translate("Dialog__preference", u"px", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab__padding), QCoreApplication.translate("Dialog__preference", u"Padding", None))
        self.groupBox__note.setTitle(QCoreApplication.translate("Dialog__preference", u"Note", None))
        self.label__note_font_size.setText(QCoreApplication.translate("Dialog__preference", u"Font Size", None))
        self.label__note_font_style.setText(QCoreApplication.translate("Dialog__preference", u"Font Style", None))
        self.groupBox__tags.setTitle(QCoreApplication.translate("Dialog__preference", u"Tags", None))
        self.label__tags_font_size.setText(QCoreApplication.translate("Dialog__preference", u"Font Size", None))
        self.label__tags_font_style.setText(QCoreApplication.translate("Dialog__preference", u"Font Style", None))
        self.groupBox__debug.setTitle(QCoreApplication.translate("Dialog__preference", u"Debug", None))
        self.label__debug_font_size.setText(QCoreApplication.translate("Dialog__preference", u"Font Size", None))
        self.label__debug_font_style.setText(QCoreApplication.translate("Dialog__preference", u"Font Style", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_text), QCoreApplication.translate("Dialog__preference", u"Text", None))
    # retranslateUi

