# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video_player.ui',
# licensing of 'video_player.ui' applies.
#
# Created: Fri May 29 21:03:13 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form__video_player(object):
    def setupUi(self, Form__video_player):
        Form__video_player.setObjectName("Form__video_player")
        Form__video_player.resize(964, 593)
        font = QtGui.QFont()
        font.setPointSize(11)
        Form__video_player.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/video_player_main/icons/viewport_logo_trans.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form__video_player.setWindowIcon(icon)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form__video_player)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter__vertical = QtWidgets.QSplitter(Form__video_player)
        self.splitter__vertical.setOrientation(QtCore.Qt.Vertical)
        self.splitter__vertical.setHandleWidth(3)
        self.splitter__vertical.setObjectName("splitter__vertical")
        self.splitter__horizontal = QtWidgets.QSplitter(self.splitter__vertical)
        self.splitter__horizontal.setOrientation(QtCore.Qt.Horizontal)
        self.splitter__horizontal.setHandleWidth(3)
        self.splitter__horizontal.setObjectName("splitter__horizontal")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.splitter__horizontal)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout__viewport = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout__viewport.setSpacing(1)
        self.horizontalLayout__viewport.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout__viewport.setObjectName("horizontalLayout__viewport")
        self.layoutWidget = QtWidgets.QWidget(self.splitter__horizontal)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget__playlist = QtWidgets.QListWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.listWidget__playlist.setFont(font)
        self.listWidget__playlist.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget__playlist.setObjectName("listWidget__playlist")
        self.verticalLayout.addWidget(self.listWidget__playlist)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setContentsMargins(3, -1, 3, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton__add_playlist = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton__add_playlist.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton__add_playlist.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/video_player_main/icons/ic_playlist_add_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton__add_playlist.setIcon(icon1)
        self.pushButton__add_playlist.setIconSize(QtCore.QSize(20, 20))
        self.pushButton__add_playlist.setFlat(True)
        self.pushButton__add_playlist.setObjectName("pushButton__add_playlist")
        self.horizontalLayout_4.addWidget(self.pushButton__add_playlist)
        spacerItem = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButton__del_playlist = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton__del_playlist.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton__del_playlist.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/video_player_main/icons/ic_delete_forever_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton__del_playlist.setIcon(icon2)
        self.pushButton__del_playlist.setIconSize(QtCore.QSize(20, 20))
        self.pushButton__del_playlist.setFlat(True)
        self.pushButton__del_playlist.setObjectName("pushButton__del_playlist")
        self.horizontalLayout_4.addWidget(self.pushButton__del_playlist)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter__vertical)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setContentsMargins(3, -1, 3, 3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(1)
        self.horizontalLayout_3.setContentsMargins(3, 3, 3, 1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalSlider__progress = QtWidgets.QSlider(self.layoutWidget1)
        self.horizontalSlider__progress.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider__progress.setObjectName("horizontalSlider__progress")
        self.horizontalLayout_3.addWidget(self.horizontalSlider__progress)
        spacerItem1 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton__volume = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton__volume.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton__volume.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/video_player_main/icons/ic_volume_up_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton__volume.setIcon(icon3)
        self.pushButton__volume.setIconSize(QtCore.QSize(20, 20))
        self.pushButton__volume.setCheckable(True)
        self.pushButton__volume.setFlat(True)
        self.pushButton__volume.setObjectName("pushButton__volume")
        self.horizontalLayout.addWidget(self.pushButton__volume)
        self.horizontalSlider__volume = QtWidgets.QSlider(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider__volume.sizePolicy().hasHeightForWidth())
        self.horizontalSlider__volume.setSizePolicy(sizePolicy)
        self.horizontalSlider__volume.setMaximum(100)
        self.horizontalSlider__volume.setProperty("value", 30)
        self.horizontalSlider__volume.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider__volume.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider__volume.setTickInterval(10)
        self.horizontalSlider__volume.setObjectName("horizontalSlider__volume")
        self.horizontalLayout.addWidget(self.horizontalSlider__volume)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(20)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton__play = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton__play.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton__play.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/video_player_main/icons/ic_play_arrow_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton__play.setIcon(icon4)
        self.pushButton__play.setIconSize(QtCore.QSize(20, 20))
        self.pushButton__play.setFlat(True)
        self.pushButton__play.setObjectName("pushButton__play")
        self.horizontalLayout_5.addWidget(self.pushButton__play)
        self.pushButton__stop = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton__stop.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton__stop.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/video_player_main/icons/ic_stop_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton__stop.setIcon(icon5)
        self.pushButton__stop.setIconSize(QtCore.QSize(20, 20))
        self.pushButton__stop.setFlat(True)
        self.pushButton__stop.setObjectName("pushButton__stop")
        self.horizontalLayout_5.addWidget(self.pushButton__stop)
        self.pushButton__previous_video = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton__previous_video.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton__previous_video.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/video_player_main/icons/ic_skip_previous_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton__previous_video.setIcon(icon6)
        self.pushButton__previous_video.setIconSize(QtCore.QSize(20, 20))
        self.pushButton__previous_video.setFlat(True)
        self.pushButton__previous_video.setObjectName("pushButton__previous_video")
        self.horizontalLayout_5.addWidget(self.pushButton__previous_video)
        self.pushButton__next_video = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton__next_video.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton__next_video.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/video_player_main/icons/ic_skip_next_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton__next_video.setIcon(icon7)
        self.pushButton__next_video.setIconSize(QtCore.QSize(20, 20))
        self.pushButton__next_video.setFlat(True)
        self.pushButton__next_video.setObjectName("pushButton__next_video")
        self.horizontalLayout_5.addWidget(self.pushButton__next_video)
        self.pushButton__playback_mode = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton__playback_mode.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton__playback_mode.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/video_player_main/icons/ic_repeat_one_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton__playback_mode.setIcon(icon8)
        self.pushButton__playback_mode.setIconSize(QtCore.QSize(20, 20))
        self.pushButton__playback_mode.setChecked(False)
        self.pushButton__playback_mode.setFlat(True)
        self.pushButton__playback_mode.setObjectName("pushButton__playback_mode")
        self.horizontalLayout_5.addWidget(self.pushButton__playback_mode)
        self.line = QtWidgets.QFrame(self.layoutWidget1)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.pushButton__full_screen = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton__full_screen.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton__full_screen.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/video_player_main/icons/ic_zoom_out_map_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton__full_screen.setIcon(icon9)
        self.pushButton__full_screen.setIconSize(QtCore.QSize(20, 20))
        self.pushButton__full_screen.setFlat(True)
        self.pushButton__full_screen.setObjectName("pushButton__full_screen")
        self.horizontalLayout_5.addWidget(self.pushButton__full_screen)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_5.addWidget(self.line_2)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.doubleSpinBox__play_speed = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.doubleSpinBox__play_speed.setCursor(QtCore.Qt.PointingHandCursor)
        self.doubleSpinBox__play_speed.setFrame(False)
        self.doubleSpinBox__play_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox__play_speed.setDecimals(1)
        self.doubleSpinBox__play_speed.setMinimum(0.1)
        self.doubleSpinBox__play_speed.setMaximum(10.0)
        self.doubleSpinBox__play_speed.setSingleStep(0.1)
        self.doubleSpinBox__play_speed.setProperty("value", 1.0)
        self.doubleSpinBox__play_speed.setObjectName("doubleSpinBox__play_speed")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox__play_speed)
        spacerItem3 = QtWidgets.QSpacerItem(18, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label__current_time = QtWidgets.QLabel(self.layoutWidget1)
        self.label__current_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label__current_time.setObjectName("label__current_time")
        self.horizontalLayout_2.addWidget(self.label__current_time)
        self.label__sep = QtWidgets.QLabel(self.layoutWidget1)
        self.label__sep.setAlignment(QtCore.Qt.AlignCenter)
        self.label__sep.setObjectName("label__sep")
        self.horizontalLayout_2.addWidget(self.label__sep)
        self.label__total_time = QtWidgets.QLabel(self.layoutWidget1)
        self.label__total_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label__total_time.setObjectName("label__total_time")
        self.horizontalLayout_2.addWidget(self.label__total_time)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.addWidget(self.splitter__vertical)

        self.retranslateUi(Form__video_player)
        QtCore.QMetaObject.connectSlotsByName(Form__video_player)

    def retranslateUi(self, Form__video_player):
        Form__video_player.setWindowTitle(QtWidgets.QApplication.translate("Form__video_player", "iHDA Video Player", None, -1))
        self.pushButton__add_playlist.setToolTip(QtWidgets.QApplication.translate("Form__video_player", "Add Video To Playlist", None, -1))
        self.pushButton__add_playlist.setStatusTip(QtWidgets.QApplication.translate("Form__video_player", "Add video to playlist.", None, -1))
        self.pushButton__del_playlist.setToolTip(QtWidgets.QApplication.translate("Form__video_player", "Delete Video From Playlist", None, -1))
        self.pushButton__del_playlist.setStatusTip(QtWidgets.QApplication.translate("Form__video_player", "Remove selected video from playlist", None, -1))
        self.pushButton__volume.setToolTip(QtWidgets.QApplication.translate("Form__video_player", "Volume", None, -1))
        self.pushButton__volume.setStatusTip(QtWidgets.QApplication.translate("Form__video_player", "It is a toggle button that can mute the sound.", None, -1))
        self.horizontalSlider__volume.setToolTip(QtWidgets.QApplication.translate("Form__video_player", "Volume", None, -1))
        self.horizontalSlider__volume.setStatusTip(QtWidgets.QApplication.translate("Form__video_player", "Adjust the volume.", None, -1))
        self.pushButton__play.setToolTip(QtWidgets.QApplication.translate("Form__video_player", "Play", None, -1))
        self.pushButton__play.setStatusTip(QtWidgets.QApplication.translate("Form__video_player", "Play the video.", None, -1))
        self.pushButton__stop.setToolTip(QtWidgets.QApplication.translate("Form__video_player", "Stop", None, -1))
        self.pushButton__stop.setStatusTip(QtWidgets.QApplication.translate("Form__video_player", "Stop playing the video.", None, -1))
        self.pushButton__previous_video.setToolTip(QtWidgets.QApplication.translate("Form__video_player", "Previous Video", None, -1))
        self.pushButton__previous_video.setStatusTip(QtWidgets.QApplication.translate("Form__video_player", "Play the previous video in the playlist.", None, -1))
        self.pushButton__next_video.setToolTip(QtWidgets.QApplication.translate("Form__video_player", "Next Video", None, -1))
        self.pushButton__next_video.setStatusTip(QtWidgets.QApplication.translate("Form__video_player", "Play the next video in the playlist.", None, -1))
        self.pushButton__playback_mode.setToolTip(QtWidgets.QApplication.translate("Form__video_player", "Playback Mode", None, -1))
        self.pushButton__playback_mode.setStatusTip(QtWidgets.QApplication.translate("Form__video_player", "Set the playback mode.", None, -1))
        self.pushButton__full_screen.setToolTip(QtWidgets.QApplication.translate("Form__video_player", "Full Screen", None, -1))
        self.pushButton__full_screen.setStatusTip(QtWidgets.QApplication.translate("Form__video_player", "You can view the video full-screen.", None, -1))
        self.doubleSpinBox__play_speed.setToolTip(QtWidgets.QApplication.translate("Form__video_player", "Play Speed", None, -1))
        self.doubleSpinBox__play_speed.setStatusTip(QtWidgets.QApplication.translate("Form__video_player", "Adjust the video playback speed.", None, -1))
        self.doubleSpinBox__play_speed.setPrefix(QtWidgets.QApplication.translate("Form__video_player", "x", None, -1))
        self.label__current_time.setToolTip(QtWidgets.QApplication.translate("Form__video_player", "Current time of the video", None, -1))
        self.label__current_time.setText(QtWidgets.QApplication.translate("Form__video_player", "00:00:00", None, -1))
        self.label__sep.setText(QtWidgets.QApplication.translate("Form__video_player", "/", None, -1))
        self.label__total_time.setToolTip(QtWidgets.QApplication.translate("Form__video_player", "Total time of the video", None, -1))
        self.label__total_time.setText(QtWidgets.QApplication.translate("Form__video_player", "00:00:00", None, -1))

import video_player_icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form__video_player = QtWidgets.QWidget()
    ui = Ui_Form__video_player()
    ui.setupUi(Form__video_player)
    Form__video_player.show()
    sys.exit(app.exec_())

