# Generated by pyside6-uic from widgets/video_player/video_player.ui. Do not edit; regenerate instead.
# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'video_player.ui'
##
## Created by: Qt User Interface Compiler version 6.11.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDoubleSpinBox, QFrame, QHBoxLayout,
    QLabel, QListWidget, QListWidgetItem, QPushButton,
    QSizePolicy, QSlider, QSpacerItem, QSplitter,
    QVBoxLayout, QWidget)
from . import video_player_icons_rc

class Ui_Form__video_player(object):
    def setupUi(self, Form__video_player):
        if not Form__video_player.objectName():
            Form__video_player.setObjectName(u"Form__video_player")
        Form__video_player.resize(964, 593)
        font = QFont()
        font.setPointSize(11)
        Form__video_player.setFont(font)
        icon = QIcon()
        icon.addFile(u":/video_player_main/icons/viewport_logo_trans.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        Form__video_player.setWindowIcon(icon)
        self.verticalLayout_3 = QVBoxLayout(Form__video_player)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.splitter__vertical = QSplitter(Form__video_player)
        self.splitter__vertical.setObjectName(u"splitter__vertical")
        self.splitter__vertical.setOrientation(Qt.Orientation.Vertical)
        self.splitter__vertical.setHandleWidth(3)
        self.splitter__horizontal = QSplitter(self.splitter__vertical)
        self.splitter__horizontal.setObjectName(u"splitter__horizontal")
        self.splitter__horizontal.setOrientation(Qt.Orientation.Horizontal)
        self.splitter__horizontal.setHandleWidth(3)
        self.horizontalLayoutWidget = QWidget(self.splitter__horizontal)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayout__viewport = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout__viewport.setSpacing(1)
        self.horizontalLayout__viewport.setObjectName(u"horizontalLayout__viewport")
        self.horizontalLayout__viewport.setContentsMargins(0, 0, 0, 0)
        self.splitter__horizontal.addWidget(self.horizontalLayoutWidget)
        self.layoutWidget = QWidget(self.splitter__horizontal)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.verticalLayout = QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 3)
        self.listWidget__playlist = QListWidget(self.layoutWidget)
        self.listWidget__playlist.setObjectName(u"listWidget__playlist")
        font1 = QFont()
        font1.setFamilies([u"MS Shell Dlg 2"])
        font1.setPointSize(11)
        self.listWidget__playlist.setFont(font1)
        self.listWidget__playlist.setFrameShape(QFrame.Shape.NoFrame)

        self.verticalLayout.addWidget(self.listWidget__playlist)

        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(3, -1, 3, -1)
        self.pushButton__add_playlist = QPushButton(self.layoutWidget)
        self.pushButton__add_playlist.setObjectName(u"pushButton__add_playlist")
        self.pushButton__add_playlist.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon1 = QIcon()
        icon1.addFile(u":/video_player_main/icons/ic_playlist_add_white.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton__add_playlist.setIcon(icon1)
        self.pushButton__add_playlist.setIconSize(QSize(20, 20))
        self.pushButton__add_playlist.setFlat(True)

        self.horizontalLayout_4.addWidget(self.pushButton__add_playlist)

        self.horizontalSpacer_4 = QSpacerItem(40, 10, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_4.addItem(self.horizontalSpacer_4)

        self.pushButton__del_playlist = QPushButton(self.layoutWidget)
        self.pushButton__del_playlist.setObjectName(u"pushButton__del_playlist")
        self.pushButton__del_playlist.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon2 = QIcon()
        icon2.addFile(u":/video_player_main/icons/ic_delete_forever_white.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton__del_playlist.setIcon(icon2)
        self.pushButton__del_playlist.setIconSize(QSize(20, 20))
        self.pushButton__del_playlist.setFlat(True)

        self.horizontalLayout_4.addWidget(self.pushButton__del_playlist)


        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.splitter__horizontal.addWidget(self.layoutWidget)
        self.splitter__vertical.addWidget(self.splitter__horizontal)
        self.layoutWidget1 = QWidget(self.splitter__vertical)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.verticalLayout_2 = QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(3, 0, 3, 3)
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setSpacing(1)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(3, 3, 3, 1)
        self.horizontalSlider__progress = QSlider(self.layoutWidget1)
        self.horizontalSlider__progress.setObjectName(u"horizontalSlider__progress")
        self.horizontalSlider__progress.setOrientation(Qt.Orientation.Horizontal)

        self.horizontalLayout_3.addWidget(self.horizontalSlider__progress)

        self.horizontalSpacer = QSpacerItem(10, 10, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.pushButton__volume = QPushButton(self.layoutWidget1)
        self.pushButton__volume.setObjectName(u"pushButton__volume")
        self.pushButton__volume.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon3 = QIcon()
        icon3.addFile(u":/video_player_main/icons/ic_volume_up_white.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton__volume.setIcon(icon3)
        self.pushButton__volume.setIconSize(QSize(20, 20))
        self.pushButton__volume.setCheckable(True)
        self.pushButton__volume.setFlat(True)

        self.horizontalLayout.addWidget(self.pushButton__volume)

        self.horizontalSlider__volume = QSlider(self.layoutWidget1)
        self.horizontalSlider__volume.setObjectName(u"horizontalSlider__volume")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider__volume.sizePolicy().hasHeightForWidth())
        self.horizontalSlider__volume.setSizePolicy(sizePolicy)
        self.horizontalSlider__volume.setMaximum(100)
        self.horizontalSlider__volume.setValue(30)
        self.horizontalSlider__volume.setOrientation(Qt.Orientation.Horizontal)
        self.horizontalSlider__volume.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.horizontalSlider__volume.setTickInterval(10)

        self.horizontalLayout.addWidget(self.horizontalSlider__volume)


        self.horizontalLayout_3.addLayout(self.horizontalLayout)


        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.horizontalLayout_8 = QHBoxLayout()
        self.horizontalLayout_8.setSpacing(3)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_8.addItem(self.horizontalSpacer_3)

        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setSpacing(20)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.pushButton__play = QPushButton(self.layoutWidget1)
        self.pushButton__play.setObjectName(u"pushButton__play")
        self.pushButton__play.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon4 = QIcon()
        icon4.addFile(u":/video_player_main/icons/ic_play_arrow_white.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton__play.setIcon(icon4)
        self.pushButton__play.setIconSize(QSize(20, 20))
        self.pushButton__play.setFlat(True)

        self.horizontalLayout_5.addWidget(self.pushButton__play)

        self.pushButton__stop = QPushButton(self.layoutWidget1)
        self.pushButton__stop.setObjectName(u"pushButton__stop")
        self.pushButton__stop.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon5 = QIcon()
        icon5.addFile(u":/video_player_main/icons/ic_stop_white.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton__stop.setIcon(icon5)
        self.pushButton__stop.setIconSize(QSize(20, 20))
        self.pushButton__stop.setFlat(True)

        self.horizontalLayout_5.addWidget(self.pushButton__stop)

        self.pushButton__previous_video = QPushButton(self.layoutWidget1)
        self.pushButton__previous_video.setObjectName(u"pushButton__previous_video")
        self.pushButton__previous_video.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon6 = QIcon()
        icon6.addFile(u":/video_player_main/icons/ic_skip_previous_white.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton__previous_video.setIcon(icon6)
        self.pushButton__previous_video.setIconSize(QSize(20, 20))
        self.pushButton__previous_video.setFlat(True)

        self.horizontalLayout_5.addWidget(self.pushButton__previous_video)

        self.pushButton__next_video = QPushButton(self.layoutWidget1)
        self.pushButton__next_video.setObjectName(u"pushButton__next_video")
        self.pushButton__next_video.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon7 = QIcon()
        icon7.addFile(u":/video_player_main/icons/ic_skip_next_white.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton__next_video.setIcon(icon7)
        self.pushButton__next_video.setIconSize(QSize(20, 20))
        self.pushButton__next_video.setFlat(True)

        self.horizontalLayout_5.addWidget(self.pushButton__next_video)

        self.pushButton__playback_mode = QPushButton(self.layoutWidget1)
        self.pushButton__playback_mode.setObjectName(u"pushButton__playback_mode")
        self.pushButton__playback_mode.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon8 = QIcon()
        icon8.addFile(u":/video_player_main/icons/ic_repeat_one_white.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton__playback_mode.setIcon(icon8)
        self.pushButton__playback_mode.setIconSize(QSize(20, 20))
        self.pushButton__playback_mode.setChecked(False)
        self.pushButton__playback_mode.setFlat(True)

        self.horizontalLayout_5.addWidget(self.pushButton__playback_mode)

        self.line = QFrame(self.layoutWidget1)
        self.line.setObjectName(u"line")
        self.line.setFrameShape(QFrame.Shape.VLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)

        self.horizontalLayout_5.addWidget(self.line)

        self.pushButton__full_screen = QPushButton(self.layoutWidget1)
        self.pushButton__full_screen.setObjectName(u"pushButton__full_screen")
        self.pushButton__full_screen.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon9 = QIcon()
        icon9.addFile(u":/video_player_main/icons/ic_zoom_out_map_white.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton__full_screen.setIcon(icon9)
        self.pushButton__full_screen.setIconSize(QSize(20, 20))
        self.pushButton__full_screen.setFlat(True)

        self.horizontalLayout_5.addWidget(self.pushButton__full_screen)

        self.line_2 = QFrame(self.layoutWidget1)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setFrameShape(QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)

        self.horizontalLayout_5.addWidget(self.line_2)


        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)

        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.doubleSpinBox__play_speed = QDoubleSpinBox(self.layoutWidget1)
        self.doubleSpinBox__play_speed.setObjectName(u"doubleSpinBox__play_speed")
        self.doubleSpinBox__play_speed.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.doubleSpinBox__play_speed.setFrame(False)
        self.doubleSpinBox__play_speed.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.doubleSpinBox__play_speed.setDecimals(1)
        self.doubleSpinBox__play_speed.setMinimum(0.100000000000000)
        self.doubleSpinBox__play_speed.setMaximum(10.000000000000000)
        self.doubleSpinBox__play_speed.setSingleStep(0.100000000000000)
        self.doubleSpinBox__play_speed.setValue(1.000000000000000)

        self.horizontalLayout_6.addWidget(self.doubleSpinBox__play_speed)

        self.horizontalSpacer_2 = QSpacerItem(18, 13, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_6.addItem(self.horizontalSpacer_2)


        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)


        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)

        self.horizontalSpacer_5 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_8.addItem(self.horizontalSpacer_5)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.label__current_time = QLabel(self.layoutWidget1)
        self.label__current_time.setObjectName(u"label__current_time")
        self.label__current_time.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_2.addWidget(self.label__current_time)

        self.label__sep = QLabel(self.layoutWidget1)
        self.label__sep.setObjectName(u"label__sep")
        self.label__sep.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_2.addWidget(self.label__sep)

        self.label__total_time = QLabel(self.layoutWidget1)
        self.label__total_time.setObjectName(u"label__total_time")
        self.label__total_time.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_2.addWidget(self.label__total_time)


        self.horizontalLayout_8.addLayout(self.horizontalLayout_2)


        self.verticalLayout_2.addLayout(self.horizontalLayout_8)

        self.splitter__vertical.addWidget(self.layoutWidget1)

        self.verticalLayout_3.addWidget(self.splitter__vertical)


        self.retranslateUi(Form__video_player)

        QMetaObject.connectSlotsByName(Form__video_player)
    # setupUi

    def retranslateUi(self, Form__video_player):
        Form__video_player.setWindowTitle(QCoreApplication.translate("Form__video_player", u"iHDA Video Player", None))
#if QT_CONFIG(tooltip)
        self.pushButton__add_playlist.setToolTip(QCoreApplication.translate("Form__video_player", u"Add Video To Playlist", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton__add_playlist.setStatusTip(QCoreApplication.translate("Form__video_player", u"Add video to playlist.", None))
#endif // QT_CONFIG(statustip)
        self.pushButton__add_playlist.setText("")
#if QT_CONFIG(tooltip)
        self.pushButton__del_playlist.setToolTip(QCoreApplication.translate("Form__video_player", u"Delete Video From Playlist", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton__del_playlist.setStatusTip(QCoreApplication.translate("Form__video_player", u"Remove selected video from playlist", None))
#endif // QT_CONFIG(statustip)
        self.pushButton__del_playlist.setText("")
#if QT_CONFIG(tooltip)
        self.pushButton__volume.setToolTip(QCoreApplication.translate("Form__video_player", u"Volume", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton__volume.setStatusTip(QCoreApplication.translate("Form__video_player", u"It is a toggle button that can mute the sound.", None))
#endif // QT_CONFIG(statustip)
        self.pushButton__volume.setText("")
#if QT_CONFIG(tooltip)
        self.horizontalSlider__volume.setToolTip(QCoreApplication.translate("Form__video_player", u"Volume", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.horizontalSlider__volume.setStatusTip(QCoreApplication.translate("Form__video_player", u"Adjust the volume.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(tooltip)
        self.pushButton__play.setToolTip(QCoreApplication.translate("Form__video_player", u"Play", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton__play.setStatusTip(QCoreApplication.translate("Form__video_player", u"Play the video.", None))
#endif // QT_CONFIG(statustip)
        self.pushButton__play.setText("")
#if QT_CONFIG(tooltip)
        self.pushButton__stop.setToolTip(QCoreApplication.translate("Form__video_player", u"Stop", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton__stop.setStatusTip(QCoreApplication.translate("Form__video_player", u"Stop playing the video.", None))
#endif // QT_CONFIG(statustip)
        self.pushButton__stop.setText("")
#if QT_CONFIG(tooltip)
        self.pushButton__previous_video.setToolTip(QCoreApplication.translate("Form__video_player", u"Previous Video", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton__previous_video.setStatusTip(QCoreApplication.translate("Form__video_player", u"Play the previous video in the playlist.", None))
#endif // QT_CONFIG(statustip)
        self.pushButton__previous_video.setText("")
#if QT_CONFIG(tooltip)
        self.pushButton__next_video.setToolTip(QCoreApplication.translate("Form__video_player", u"Next Video", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton__next_video.setStatusTip(QCoreApplication.translate("Form__video_player", u"Play the next video in the playlist.", None))
#endif // QT_CONFIG(statustip)
        self.pushButton__next_video.setText("")
#if QT_CONFIG(tooltip)
        self.pushButton__playback_mode.setToolTip(QCoreApplication.translate("Form__video_player", u"Playback Mode", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton__playback_mode.setStatusTip(QCoreApplication.translate("Form__video_player", u"Set the playback mode.", None))
#endif // QT_CONFIG(statustip)
        self.pushButton__playback_mode.setText("")
#if QT_CONFIG(tooltip)
        self.pushButton__full_screen.setToolTip(QCoreApplication.translate("Form__video_player", u"Full Screen", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton__full_screen.setStatusTip(QCoreApplication.translate("Form__video_player", u"You can view the video full-screen.", None))
#endif // QT_CONFIG(statustip)
        self.pushButton__full_screen.setText("")
#if QT_CONFIG(tooltip)
        self.doubleSpinBox__play_speed.setToolTip(QCoreApplication.translate("Form__video_player", u"Play Speed", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.doubleSpinBox__play_speed.setStatusTip(QCoreApplication.translate("Form__video_player", u"Adjust the video playback speed.", None))
#endif // QT_CONFIG(statustip)
        self.doubleSpinBox__play_speed.setPrefix(QCoreApplication.translate("Form__video_player", u"x", None))
#if QT_CONFIG(tooltip)
        self.label__current_time.setToolTip(QCoreApplication.translate("Form__video_player", u"Current time of the video", None))
#endif // QT_CONFIG(tooltip)
        self.label__current_time.setText(QCoreApplication.translate("Form__video_player", u"00:00:00", None))
        self.label__sep.setText(QCoreApplication.translate("Form__video_player", u"/", None))
#if QT_CONFIG(tooltip)
        self.label__total_time.setToolTip(QCoreApplication.translate("Form__video_player", u"Total time of the video", None))
#endif // QT_CONFIG(tooltip)
        self.label__total_time.setText(QCoreApplication.translate("Form__video_player", u"00:00:00", None))
    # retranslateUi

