# Generated by pyside6-uic from widgets/detail_view/detail_view.ui. Do not edit; regenerate instead.
# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'detail_view.ui'
##
## Created by: Qt User Interface Compiler version 6.11.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QHBoxLayout, QLabel,
    QSizePolicy, QTextBrowser, QVBoxLayout, QWidget)
from . import detail_view_rc

class Ui_Dialog__detail_view(object):
    def setupUi(self, Dialog__detail_view):
        if not Dialog__detail_view.objectName():
            Dialog__detail_view.setObjectName(u"Dialog__detail_view")
        Dialog__detail_view.resize(869, 524)
        font = QFont()
        font.setPointSize(11)
        Dialog__detail_view.setFont(font)
        icon = QIcon()
        icon.addFile(u":/detail_view_main/icons/viewport_logo_trans.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        Dialog__detail_view.setWindowIcon(icon)
        self.verticalLayout_2 = QVBoxLayout(Dialog__detail_view)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.label__pixmap = QLabel(Dialog__detail_view)
        self.label__pixmap.setObjectName(u"label__pixmap")
        self.label__pixmap.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.label__pixmap)


        self.horizontalLayout.addLayout(self.verticalLayout)

        self.textBrowser__detail = QTextBrowser(Dialog__detail_view)
        self.textBrowser__detail.setObjectName(u"textBrowser__detail")
        self.textBrowser__detail.setTabStopDistance(40.000000000000000)

        self.horizontalLayout.addWidget(self.textBrowser__detail)


        self.verticalLayout_2.addLayout(self.horizontalLayout)


        self.retranslateUi(Dialog__detail_view)

        QMetaObject.connectSlotsByName(Dialog__detail_view)
    # setupUi

    def retranslateUi(self, Dialog__detail_view):
        Dialog__detail_view.setWindowTitle(QCoreApplication.translate("Dialog__detail_view", u"iHDA Detail View", None))
        self.label__pixmap.setText("")
    # retranslateUi

