# Generated by pyside6-uic from widgets/web_view/web_view.ui. Do not edit; regenerate instead.
# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'web_view.ui'
##
## Created by: Qt User Interface Compiler version 6.11.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWebEngineWidgets import QWebEngineView
from PySide6.QtWidgets import (QApplication, QHBoxLayout, QLineEdit, QPushButton,
    QSizePolicy, QSpacerItem, QSplitter, QVBoxLayout,
    QWidget)
from . import web_view_icons_rc

class Ui_Form__web(object):
    def setupUi(self, Form__web):
        if not Form__web.objectName():
            Form__web.setObjectName(u"Form__web")
        Form__web.resize(646, 423)
        font = QFont()
        font.setPointSize(11)
        Form__web.setFont(font)
        icon = QIcon()
        icon.addFile(u":/web_view_main/icons/viewport_logo_trans.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        Form__web.setWindowIcon(icon)
        self.verticalLayout_3 = QVBoxLayout(Form__web)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.splitter__webview_whole_vertical = QSplitter(Form__web)
        self.splitter__webview_whole_vertical.setObjectName(u"splitter__webview_whole_vertical")
        self.splitter__webview_whole_vertical.setOrientation(Qt.Orientation.Vertical)
        self.splitter__webview_whole_vertical.setHandleWidth(3)
        self.layoutWidget = QWidget(self.splitter__webview_whole_vertical)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.verticalLayout_2 = QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(3, -1, 3, -1)
        self.pushButton__back_page = QPushButton(self.layoutWidget)
        self.pushButton__back_page.setObjectName(u"pushButton__back_page")
        self.pushButton__back_page.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon1 = QIcon()
        icon1.addFile(u":/web_view_main/icons/ic_arrow_back_white.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton__back_page.setIcon(icon1)
        self.pushButton__back_page.setIconSize(QSize(20, 20))
        self.pushButton__back_page.setFlat(True)

        self.horizontalLayout_2.addWidget(self.pushButton__back_page)

        self.pushButton__forward_page = QPushButton(self.layoutWidget)
        self.pushButton__forward_page.setObjectName(u"pushButton__forward_page")
        self.pushButton__forward_page.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon2 = QIcon()
        icon2.addFile(u":/web_view_main/icons/ic_arrow_forward_white.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton__forward_page.setIcon(icon2)
        self.pushButton__forward_page.setIconSize(QSize(20, 20))
        self.pushButton__forward_page.setFlat(True)

        self.horizontalLayout_2.addWidget(self.pushButton__forward_page)

        self.pushButton__refresh_page = QPushButton(self.layoutWidget)
        self.pushButton__refresh_page.setObjectName(u"pushButton__refresh_page")
        self.pushButton__refresh_page.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon3 = QIcon()
        icon3.addFile(u":/web_view_main/icons/ic_refresh_white.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton__refresh_page.setIcon(icon3)
        self.pushButton__refresh_page.setIconSize(QSize(20, 20))
        self.pushButton__refresh_page.setFlat(True)

        self.horizontalLayout_2.addWidget(self.pushButton__refresh_page)

        self.pushButton__close_page = QPushButton(self.layoutWidget)
        self.pushButton__close_page.setObjectName(u"pushButton__close_page")
        self.pushButton__close_page.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon4 = QIcon()
        icon4.addFile(u":/web_view_main/icons/ic_close_white.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton__close_page.setIcon(icon4)
        self.pushButton__close_page.setIconSize(QSize(20, 20))
        self.pushButton__close_page.setFlat(True)

        self.horizontalLayout_2.addWidget(self.pushButton__close_page)

        self.pushButton__home_page = QPushButton(self.layoutWidget)
        self.pushButton__home_page.setObjectName(u"pushButton__home_page")
        self.pushButton__home_page.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon5 = QIcon()
        icon5.addFile(u":/web_view_main/icons/ic_home_white.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton__home_page.setIcon(icon5)
        self.pushButton__home_page.setIconSize(QSize(20, 20))
        self.pushButton__home_page.setFlat(True)

        self.horizontalLayout_2.addWidget(self.pushButton__home_page)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer)

        self.pushButton__zoomin = QPushButton(self.layoutWidget)
        self.pushButton__zoomin.setObjectName(u"pushButton__zoomin")
        self.pushButton__zoomin.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon6 = QIcon()
        icon6.addFile(u":/web_view_main/icons/ic_zoom_in_white.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton__zoomin.setIcon(icon6)
        self.pushButton__zoomin.setIconSize(QSize(20, 20))
        self.pushButton__zoomin.setFlat(True)

        self.horizontalLayout_2.addWidget(self.pushButton__zoomin)

        self.pushButton__zoomout = QPushButton(self.layoutWidget)
        self.pushButton__zoomout.setObjectName(u"pushButton__zoomout")
        self.pushButton__zoomout.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon7 = QIcon()
        icon7.addFile(u":/web_view_main/icons/ic_zoom_out_white.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton__zoomout.setIcon(icon7)
        self.pushButton__zoomout.setIconSize(QSize(20, 20))
        self.pushButton__zoomout.setFlat(True)

        self.horizontalLayout_2.addWidget(self.pushButton__zoomout)

        self.pushButton__reset_zoom = QPushButton(self.layoutWidget)
        self.pushButton__reset_zoom.setObjectName(u"pushButton__reset_zoom")
        self.pushButton__reset_zoom.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon8 = QIcon()
        icon8.addFile(u":/web_view_main/icons/ic_search_white.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton__reset_zoom.setIcon(icon8)
        self.pushButton__reset_zoom.setIconSize(QSize(20, 20))
        self.pushButton__reset_zoom.setFlat(True)

        self.horizontalLayout_2.addWidget(self.pushButton__reset_zoom)


        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(3, -1, 3, 2)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.pushButton__help = QPushButton(self.layoutWidget)
        self.pushButton__help.setObjectName(u"pushButton__help")
        self.pushButton__help.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon9 = QIcon()
        icon9.addFile(u":/web_view_main/icons/houdini_logo.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton__help.setIcon(icon9)
        self.pushButton__help.setIconSize(QSize(20, 20))
        self.pushButton__help.setFlat(True)

        self.horizontalLayout.addWidget(self.pushButton__help)

        self.pushButton__sidefx = QPushButton(self.layoutWidget)
        self.pushButton__sidefx.setObjectName(u"pushButton__sidefx")
        self.pushButton__sidefx.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon10 = QIcon()
        icon10.addFile(u":/web_view_main/icons/news.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton__sidefx.setIcon(icon10)
        self.pushButton__sidefx.setIconSize(QSize(20, 20))
        self.pushButton__sidefx.setFlat(True)

        self.horizontalLayout.addWidget(self.pushButton__sidefx)

        self.pushButton__odforce = QPushButton(self.layoutWidget)
        self.pushButton__odforce.setObjectName(u"pushButton__odforce")
        self.pushButton__odforce.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon11 = QIcon()
        icon11.addFile(u":/web_view_main/icons/odforce.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton__odforce.setIcon(icon11)
        self.pushButton__odforce.setIconSize(QSize(20, 20))
        self.pushButton__odforce.setFlat(True)

        self.horizontalLayout.addWidget(self.pushButton__odforce)

        self.pushButton__google = QPushButton(self.layoutWidget)
        self.pushButton__google.setObjectName(u"pushButton__google")
        self.pushButton__google.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon12 = QIcon()
        icon12.addFile(u":/web_view_main/icons/google.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton__google.setIcon(icon12)
        self.pushButton__google.setIconSize(QSize(20, 20))
        self.pushButton__google.setFlat(True)

        self.horizontalLayout.addWidget(self.pushButton__google)

        self.pushButton__translation = QPushButton(self.layoutWidget)
        self.pushButton__translation.setObjectName(u"pushButton__translation")
        self.pushButton__translation.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon13 = QIcon()
        icon13.addFile(u":/web_view_main/icons/ic_g_translate_white.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton__translation.setIcon(icon13)
        self.pushButton__translation.setIconSize(QSize(20, 20))
        self.pushButton__translation.setFlat(True)

        self.horizontalLayout.addWidget(self.pushButton__translation)

        self.pushButton__youtube = QPushButton(self.layoutWidget)
        self.pushButton__youtube.setObjectName(u"pushButton__youtube")
        self.pushButton__youtube.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon14 = QIcon()
        icon14.addFile(u":/web_view_main/icons/youtube.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton__youtube.setIcon(icon14)
        self.pushButton__youtube.setIconSize(QSize(20, 20))
        self.pushButton__youtube.setFlat(True)

        self.horizontalLayout.addWidget(self.pushButton__youtube)

        self.pushButton__vimeo = QPushButton(self.layoutWidget)
        self.pushButton__vimeo.setObjectName(u"pushButton__vimeo")
        self.pushButton__vimeo.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon15 = QIcon()
        icon15.addFile(u":/web_view_main/icons/vimeo.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton__vimeo.setIcon(icon15)
        self.pushButton__vimeo.setIconSize(QSize(20, 20))
        self.pushButton__vimeo.setFlat(True)

        self.horizontalLayout.addWidget(self.pushButton__vimeo)


        self.horizontalLayout_3.addLayout(self.horizontalLayout)

        self.lineEdit__address = QLineEdit(self.layoutWidget)
        self.lineEdit__address.setObjectName(u"lineEdit__address")
        self.lineEdit__address.setClearButtonEnabled(True)

        self.horizontalLayout_3.addWidget(self.lineEdit__address)


        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.splitter__webview_whole_vertical.addWidget(self.layoutWidget)
        self.verticalLayoutWidget = QWidget(self.splitter__webview_whole_vertical)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.webEngineView__webview = QWebEngineView(self.verticalLayoutWidget)
        self.webEngineView__webview.setObjectName(u"webEngineView__webview")
        self.webEngineView__webview.setUrl(QUrl(u"about:blank"))

        self.verticalLayout.addWidget(self.webEngineView__webview)

        self.splitter__webview_whole_vertical.addWidget(self.verticalLayoutWidget)

        self.verticalLayout_3.addWidget(self.splitter__webview_whole_vertical)


        self.retranslateUi(Form__web)

        QMetaObject.connectSlotsByName(Form__web)
    # setupUi

    def retranslateUi(self, Form__web):
        Form__web.setWindowTitle(QCoreApplication.translate("Form__web", u"iHDA Web View", None))
#if QT_CONFIG(tooltip)
        self.pushButton__back_page.setToolTip(QCoreApplication.translate("Form__web", u"Back Page", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton__back_page.setStatusTip(QCoreApplication.translate("Form__web", u"back page", None))
#endif // QT_CONFIG(statustip)
        self.pushButton__back_page.setText("")
#if QT_CONFIG(tooltip)
        self.pushButton__forward_page.setToolTip(QCoreApplication.translate("Form__web", u"Forward Page", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton__forward_page.setStatusTip(QCoreApplication.translate("Form__web", u"forward page", None))
#endif // QT_CONFIG(statustip)
        self.pushButton__forward_page.setText("")
#if QT_CONFIG(tooltip)
        self.pushButton__refresh_page.setToolTip(QCoreApplication.translate("Form__web", u"Refresh Page", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton__refresh_page.setStatusTip(QCoreApplication.translate("Form__web", u"refresh page", None))
#endif // QT_CONFIG(statustip)
        self.pushButton__refresh_page.setText("")
#if QT_CONFIG(tooltip)
        self.pushButton__close_page.setToolTip(QCoreApplication.translate("Form__web", u"Close Page", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton__close_page.setStatusTip(QCoreApplication.translate("Form__web", u"close page", None))
#endif // QT_CONFIG(statustip)
        self.pushButton__close_page.setText("")
#if QT_CONFIG(tooltip)
        self.pushButton__home_page.setToolTip(QCoreApplication.translate("Form__web", u"Home", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton__home_page.setStatusTip(QCoreApplication.translate("Form__web", u"home page", None))
#endif // QT_CONFIG(statustip)
        self.pushButton__home_page.setText("")
#if QT_CONFIG(tooltip)
        self.pushButton__zoomin.setToolTip(QCoreApplication.translate("Form__web", u"zoom in", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton__zoomin.setStatusTip(QCoreApplication.translate("Form__web", u"zoom in", None))
#endif // QT_CONFIG(statustip)
        self.pushButton__zoomin.setText("")
#if QT_CONFIG(tooltip)
        self.pushButton__zoomout.setToolTip(QCoreApplication.translate("Form__web", u"zoom out", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton__zoomout.setStatusTip(QCoreApplication.translate("Form__web", u"zoom out", None))
#endif // QT_CONFIG(statustip)
        self.pushButton__zoomout.setText("")
#if QT_CONFIG(tooltip)
        self.pushButton__reset_zoom.setToolTip(QCoreApplication.translate("Form__web", u"reset zoom", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton__reset_zoom.setStatusTip(QCoreApplication.translate("Form__web", u"reset zoom", None))
#endif // QT_CONFIG(statustip)
        self.pushButton__reset_zoom.setText("")
#if QT_CONFIG(tooltip)
        self.pushButton__help.setToolTip(QCoreApplication.translate("Form__web", u"Help", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton__help.setStatusTip(QCoreApplication.translate("Form__web", u"Houdini Help", None))
#endif // QT_CONFIG(statustip)
        self.pushButton__help.setText("")
#if QT_CONFIG(tooltip)
        self.pushButton__sidefx.setToolTip(QCoreApplication.translate("Form__web", u"SideFX", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton__sidefx.setStatusTip(QCoreApplication.translate("Form__web", u"go to sidefx", None))
#endif // QT_CONFIG(statustip)
        self.pushButton__sidefx.setText("")
#if QT_CONFIG(tooltip)
        self.pushButton__odforce.setToolTip(QCoreApplication.translate("Form__web", u"ODFORCE", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton__odforce.setStatusTip(QCoreApplication.translate("Form__web", u"home page", None))
#endif // QT_CONFIG(statustip)
        self.pushButton__odforce.setText("")
#if QT_CONFIG(tooltip)
        self.pushButton__google.setToolTip(QCoreApplication.translate("Form__web", u"Google", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton__google.setStatusTip(QCoreApplication.translate("Form__web", u"go to google", None))
#endif // QT_CONFIG(statustip)
        self.pushButton__google.setText("")
#if QT_CONFIG(tooltip)
        self.pushButton__translation.setToolTip(QCoreApplication.translate("Form__web", u"Translation", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton__translation.setStatusTip(QCoreApplication.translate("Form__web", u"translation", None))
#endif // QT_CONFIG(statustip)
        self.pushButton__translation.setText("")
#if QT_CONFIG(tooltip)
        self.pushButton__youtube.setToolTip(QCoreApplication.translate("Form__web", u"Youtube", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton__youtube.setStatusTip(QCoreApplication.translate("Form__web", u"go to youtube", None))
#endif // QT_CONFIG(statustip)
        self.pushButton__youtube.setText("")
#if QT_CONFIG(tooltip)
        self.pushButton__vimeo.setToolTip(QCoreApplication.translate("Form__web", u"Vimeo", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton__vimeo.setStatusTip(QCoreApplication.translate("Form__web", u"go to vimeo", None))
#endif // QT_CONFIG(statustip)
        self.pushButton__vimeo.setText("")
        self.lineEdit__address.setText(QCoreApplication.translate("Form__web", u"https://www.google.co.kr/?gws_rd=ssl", None))
    # retranslateUi

