# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'web_view.ui',
# licensing of 'web_view.ui' applies.
#
# Created: Mon May 25 17:32:10 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form__web(object):
    def setupUi(self, Form__web):
        Form__web.setObjectName("Form__web")
        Form__web.resize(646, 423)
        font = QtGui.QFont()
        font.setPointSize(11)
        Form__web.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/web_view_main/icons/viewport_logo_trans.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form__web.setWindowIcon(icon)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form__web)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter__webview_whole_vertical = QtWidgets.QSplitter(Form__web)
        self.splitter__webview_whole_vertical.setOrientation(QtCore.Qt.Vertical)
        self.splitter__webview_whole_vertical.setHandleWidth(3)
        self.splitter__webview_whole_vertical.setObjectName("splitter__webview_whole_vertical")
        self.layoutWidget = QtWidgets.QWidget(self.splitter__webview_whole_vertical)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(3, -1, 3, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton__back_page = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton__back_page.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton__back_page.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/web_view_main/icons/ic_arrow_back_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton__back_page.setIcon(icon1)
        self.pushButton__back_page.setIconSize(QtCore.QSize(20, 20))
        self.pushButton__back_page.setFlat(True)
        self.pushButton__back_page.setObjectName("pushButton__back_page")
        self.horizontalLayout_2.addWidget(self.pushButton__back_page)
        self.pushButton__forward_page = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton__forward_page.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton__forward_page.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/web_view_main/icons/ic_arrow_forward_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton__forward_page.setIcon(icon2)
        self.pushButton__forward_page.setIconSize(QtCore.QSize(20, 20))
        self.pushButton__forward_page.setFlat(True)
        self.pushButton__forward_page.setObjectName("pushButton__forward_page")
        self.horizontalLayout_2.addWidget(self.pushButton__forward_page)
        self.pushButton__refresh_page = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton__refresh_page.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton__refresh_page.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/web_view_main/icons/ic_refresh_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton__refresh_page.setIcon(icon3)
        self.pushButton__refresh_page.setIconSize(QtCore.QSize(20, 20))
        self.pushButton__refresh_page.setFlat(True)
        self.pushButton__refresh_page.setObjectName("pushButton__refresh_page")
        self.horizontalLayout_2.addWidget(self.pushButton__refresh_page)
        self.pushButton__close_page = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton__close_page.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton__close_page.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/web_view_main/icons/ic_close_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton__close_page.setIcon(icon4)
        self.pushButton__close_page.setIconSize(QtCore.QSize(20, 20))
        self.pushButton__close_page.setFlat(True)
        self.pushButton__close_page.setObjectName("pushButton__close_page")
        self.horizontalLayout_2.addWidget(self.pushButton__close_page)
        self.pushButton__home_page = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton__home_page.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton__home_page.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/web_view_main/icons/ic_home_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton__home_page.setIcon(icon5)
        self.pushButton__home_page.setIconSize(QtCore.QSize(20, 20))
        self.pushButton__home_page.setFlat(True)
        self.pushButton__home_page.setObjectName("pushButton__home_page")
        self.horizontalLayout_2.addWidget(self.pushButton__home_page)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton__zoomin = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton__zoomin.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton__zoomin.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/web_view_main/icons/ic_zoom_in_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton__zoomin.setIcon(icon6)
        self.pushButton__zoomin.setIconSize(QtCore.QSize(20, 20))
        self.pushButton__zoomin.setFlat(True)
        self.pushButton__zoomin.setObjectName("pushButton__zoomin")
        self.horizontalLayout_2.addWidget(self.pushButton__zoomin)
        self.pushButton__zoomout = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton__zoomout.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton__zoomout.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/web_view_main/icons/ic_zoom_out_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton__zoomout.setIcon(icon7)
        self.pushButton__zoomout.setIconSize(QtCore.QSize(20, 20))
        self.pushButton__zoomout.setFlat(True)
        self.pushButton__zoomout.setObjectName("pushButton__zoomout")
        self.horizontalLayout_2.addWidget(self.pushButton__zoomout)
        self.pushButton__reset_zoom = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton__reset_zoom.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton__reset_zoom.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/web_view_main/icons/ic_search_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton__reset_zoom.setIcon(icon8)
        self.pushButton__reset_zoom.setIconSize(QtCore.QSize(20, 20))
        self.pushButton__reset_zoom.setFlat(True)
        self.pushButton__reset_zoom.setObjectName("pushButton__reset_zoom")
        self.horizontalLayout_2.addWidget(self.pushButton__reset_zoom)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(3, -1, 3, 2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton__help = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton__help.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton__help.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/web_view_main/icons/houdini_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton__help.setIcon(icon9)
        self.pushButton__help.setIconSize(QtCore.QSize(20, 20))
        self.pushButton__help.setFlat(True)
        self.pushButton__help.setObjectName("pushButton__help")
        self.horizontalLayout.addWidget(self.pushButton__help)
        self.pushButton__sidefx = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton__sidefx.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton__sidefx.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/web_view_main/icons/news.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton__sidefx.setIcon(icon10)
        self.pushButton__sidefx.setIconSize(QtCore.QSize(20, 20))
        self.pushButton__sidefx.setFlat(True)
        self.pushButton__sidefx.setObjectName("pushButton__sidefx")
        self.horizontalLayout.addWidget(self.pushButton__sidefx)
        self.pushButton__odforce = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton__odforce.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton__odforce.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/web_view_main/icons/odforce.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton__odforce.setIcon(icon11)
        self.pushButton__odforce.setIconSize(QtCore.QSize(20, 20))
        self.pushButton__odforce.setFlat(True)
        self.pushButton__odforce.setObjectName("pushButton__odforce")
        self.horizontalLayout.addWidget(self.pushButton__odforce)
        self.pushButton__google = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton__google.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton__google.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/web_view_main/icons/google.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton__google.setIcon(icon12)
        self.pushButton__google.setIconSize(QtCore.QSize(20, 20))
        self.pushButton__google.setFlat(True)
        self.pushButton__google.setObjectName("pushButton__google")
        self.horizontalLayout.addWidget(self.pushButton__google)
        self.pushButton__translation = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton__translation.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton__translation.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/web_view_main/icons/ic_g_translate_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton__translation.setIcon(icon13)
        self.pushButton__translation.setIconSize(QtCore.QSize(20, 20))
        self.pushButton__translation.setFlat(True)
        self.pushButton__translation.setObjectName("pushButton__translation")
        self.horizontalLayout.addWidget(self.pushButton__translation)
        self.pushButton__youtube = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton__youtube.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton__youtube.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/web_view_main/icons/youtube.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton__youtube.setIcon(icon14)
        self.pushButton__youtube.setIconSize(QtCore.QSize(20, 20))
        self.pushButton__youtube.setFlat(True)
        self.pushButton__youtube.setObjectName("pushButton__youtube")
        self.horizontalLayout.addWidget(self.pushButton__youtube)
        self.pushButton__vimeo = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton__vimeo.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton__vimeo.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/web_view_main/icons/vimeo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton__vimeo.setIcon(icon15)
        self.pushButton__vimeo.setIconSize(QtCore.QSize(20, 20))
        self.pushButton__vimeo.setFlat(True)
        self.pushButton__vimeo.setObjectName("pushButton__vimeo")
        self.horizontalLayout.addWidget(self.pushButton__vimeo)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.lineEdit__address = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit__address.setClearButtonEnabled(True)
        self.lineEdit__address.setObjectName("lineEdit__address")
        self.horizontalLayout_3.addWidget(self.lineEdit__address)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter__webview_whole_vertical)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.webEngineView__webview = QWebEngineView(self.verticalLayoutWidget)
        self.webEngineView__webview.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView__webview.setObjectName("webEngineView__webview")
        self.verticalLayout.addWidget(self.webEngineView__webview)
        self.verticalLayout_3.addWidget(self.splitter__webview_whole_vertical)

        self.retranslateUi(Form__web)
        QtCore.QMetaObject.connectSlotsByName(Form__web)

    def retranslateUi(self, Form__web):
        Form__web.setWindowTitle(QtWidgets.QApplication.translate("Form__web", "iHDA Web View", None, -1))
        self.pushButton__back_page.setToolTip(QtWidgets.QApplication.translate("Form__web", "Back Page", None, -1))
        self.pushButton__back_page.setStatusTip(QtWidgets.QApplication.translate("Form__web", "back page", None, -1))
        self.pushButton__forward_page.setToolTip(QtWidgets.QApplication.translate("Form__web", "Forward Page", None, -1))
        self.pushButton__forward_page.setStatusTip(QtWidgets.QApplication.translate("Form__web", "forward page", None, -1))
        self.pushButton__refresh_page.setToolTip(QtWidgets.QApplication.translate("Form__web", "Refresh Page", None, -1))
        self.pushButton__refresh_page.setStatusTip(QtWidgets.QApplication.translate("Form__web", "refresh page", None, -1))
        self.pushButton__close_page.setToolTip(QtWidgets.QApplication.translate("Form__web", "Close Page", None, -1))
        self.pushButton__close_page.setStatusTip(QtWidgets.QApplication.translate("Form__web", "close page", None, -1))
        self.pushButton__home_page.setToolTip(QtWidgets.QApplication.translate("Form__web", "Home", None, -1))
        self.pushButton__home_page.setStatusTip(QtWidgets.QApplication.translate("Form__web", "home page", None, -1))
        self.pushButton__zoomin.setToolTip(QtWidgets.QApplication.translate("Form__web", "zoom in", None, -1))
        self.pushButton__zoomin.setStatusTip(QtWidgets.QApplication.translate("Form__web", "zoom in", None, -1))
        self.pushButton__zoomout.setToolTip(QtWidgets.QApplication.translate("Form__web", "zoom out", None, -1))
        self.pushButton__zoomout.setStatusTip(QtWidgets.QApplication.translate("Form__web", "zoom out", None, -1))
        self.pushButton__reset_zoom.setToolTip(QtWidgets.QApplication.translate("Form__web", "reset zoom", None, -1))
        self.pushButton__reset_zoom.setStatusTip(QtWidgets.QApplication.translate("Form__web", "reset zoom", None, -1))
        self.pushButton__help.setToolTip(QtWidgets.QApplication.translate("Form__web", "Help", None, -1))
        self.pushButton__help.setStatusTip(QtWidgets.QApplication.translate("Form__web", "Houdini Help", None, -1))
        self.pushButton__sidefx.setToolTip(QtWidgets.QApplication.translate("Form__web", "SideFX", None, -1))
        self.pushButton__sidefx.setStatusTip(QtWidgets.QApplication.translate("Form__web", "go to sidefx", None, -1))
        self.pushButton__odforce.setToolTip(QtWidgets.QApplication.translate("Form__web", "ODFORCE", None, -1))
        self.pushButton__odforce.setStatusTip(QtWidgets.QApplication.translate("Form__web", "home page", None, -1))
        self.pushButton__google.setToolTip(QtWidgets.QApplication.translate("Form__web", "Google", None, -1))
        self.pushButton__google.setStatusTip(QtWidgets.QApplication.translate("Form__web", "go to google", None, -1))
        self.pushButton__translation.setToolTip(QtWidgets.QApplication.translate("Form__web", "Translation", None, -1))
        self.pushButton__translation.setStatusTip(QtWidgets.QApplication.translate("Form__web", "translation", None, -1))
        self.pushButton__youtube.setToolTip(QtWidgets.QApplication.translate("Form__web", "Youtube", None, -1))
        self.pushButton__youtube.setStatusTip(QtWidgets.QApplication.translate("Form__web", "go to youtube", None, -1))
        self.pushButton__vimeo.setToolTip(QtWidgets.QApplication.translate("Form__web", "Vimeo", None, -1))
        self.pushButton__vimeo.setStatusTip(QtWidgets.QApplication.translate("Form__web", "go to vimeo", None, -1))
        self.lineEdit__address.setText(QtWidgets.QApplication.translate("Form__web", "https://www.google.co.kr/?gws_rd=ssl", None, -1))

from PySide2.QtWebEngineWidgets import QWebEngineView
import web_view_icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form__web = QtWidgets.QWidget()
    ui = Ui_Form__web()
    ui.setupUi(Form__web)
    Form__web.show()
    sys.exit(app.exec_())

